import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {parseRaw,fieldClass} from '../server/agencyzoom-raw.mjs';
import {rawImporter} from '../server/agencyzoom-import.mjs';
import {districtPilot,pilotAssignment} from '../server/district-pilot.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const db={prepare(q){let args=[];const stmt={bind(...v){args=v;return stmt},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}};return stmt},async batch(stmts){sql.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};const now=new Date().toISOString();for(const id of ['one','two'])sql.prepare('INSERT INTO cf_solo_opportunities(id,workspace_id,owner_id,contact_json,source,last_mutation_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,'qa','qa','{}','district','qa',now,now);const repo={db,scope:{workspace:'qa',actor:'qa'},sql:(q,...v)=>db.prepare(q).bind(...v),rows:async(q,...v)=>(await db.prepare(q).bind(...v).all()).results,own:async id=>{const r=sql.prepare('SELECT * FROM cf_solo_opportunities WHERE workspace_id=? AND id=?').get('qa',id);if(!r)throw new Error('unavailable');return r;}};return {sql,repo,pilot:districtPilot(repo),received:new Date(Date.now()-60000).toISOString()};}
const file=(id='100',phone='2025550199')=>({name:'AWL-'+id+'.csv',text:'Lead ID,Date,Lead Type,State,Cell Phone,Name,Current Insurance Co,Experation Date,Credit Rating,DOB,Occupation,Needs Quote\n'+[id,new Date(Date.now()-60000).toISOString(),'Automobile','CA',phone,'Synthetic Tester','Mercury','2026-12-31','EXCLUDED_CREDIT','EXCLUDED_DOB','EXCLUDED_JOB','ASAP'].join(',')});
const env={RINGCENTRAL_FROM_NUMBER:'+12025550100',RINGCENTRAL_CONVERSATION_HASH_SECRET:'synthetic-only-conversation-secret'};
function setup(){const f=fixture();f.refreshed=[];f.repo.refreshOpportunityPriority=async id=>f.refreshed.push(id);f.importer=rawImporter(f.repo,env);return f;}
test('RAW allowlist keeps insurance evidence, excludes sensitive values and infers no consent',()=>{const r=parseRaw(file());assert.equal(r.facts.line,'AUTO');assert.equal(r.facts.current_carrier,'Mercury');assert.equal(r.governance.D,3);assert.ok(!JSON.stringify(r).includes('EXCLUDED_'));assert.equal(r.contact.mobile,'+12025550199');assert.match(r.contact.contactBasis,/no SMS/);assert.equal(fieldClass('Credit Rating'),'D');assert.equal(fieldClass('Annual Miles'),'B');});
test('RAW parser accepts BOM and exact observed header defect; rejects malformed, oversized and empty headers',()=>{const f=file();assert.equal(parseRaw({...f,text:'\uFEFF'+f.text}).line,'AUTO');const observed={name:'AWL-test.csv',text:'_csv_"Lead ID","Date","Lead Type","State","Credit Rating",","Currently Insurance", ,\n"abc","'+new Date(Date.now()-60000).toISOString()+'","Auto","CA","discard","Yes", ,'};assert.equal(parseRaw(observed).facts.currently_insured,true);assert.throws(()=>parseRaw({...f,text:'"a,b\nx,y'}));assert.throws(()=>parseRaw({...f,text:'x'.repeat(65537)}),/OVERSIZED/);assert.throws(()=>parseRaw({...f,text:',,\n1,2,3'}),/INVALID RAW FILE/);});
test('RAW batch creates one durable enrollment per stable key, retries dedupe, and only SIGNAL gets priority',async()=>{const f=setup();try{const files=Array.from({length:10},(_,i)=>file(String(1000+i),'20255501'+String(i+10)));const p=await f.importer.preview({files});assert.equal(p.rows.filter(r=>r.status==='READY').length,10);const v={files,fingerprint:p.fingerprint,confirmed:true,eligible:true};const result=await f.importer.commit(v);assert.equal(result.imported,10,JSON.stringify(result));assert.equal(f.refreshed.length,result.results.filter(r=>r.cohort==='SIGNAL').length);assert.equal((await f.importer.commit(v)).duplicates,10);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM cf_solo_sources WHERE kind=?').get('district_pilot_v1').n,10);const sources=f.sql.prepare('SELECT summary_json FROM cf_solo_sources').all();assert.ok(!JSON.stringify(sources).includes('EXCLUDED_'));assert.equal((await f.pilot.report()).records.length,10);}finally{f.sql.close()}});
test('RAW one bad file does not drop good files; phone collision blocks both; TEST excluded from report',async()=>{const f=setup();try{let files=[file('valid'),{name:'bad.csv',text:'broken'}],p=await f.importer.preview({files,synthetic:true});assert.equal(p.rows[0].status,'READY');const r=await f.importer.commit({files,synthetic:true,fingerprint:p.fingerprint,eligible:true,confirmed:true});assert.equal(r.imported,1);assert.equal((await f.pilot.report()).records.length,0);files=[file('phone1','2025550188'),file('phone2','2025550188')];p=await f.importer.preview({files});assert.ok(p.rows.every(r=>r.status.startsWith('PHONE CONFLICT')));}finally{f.sql.close()}});
test('RAW fingerprint prevents changed confirmation; old leads cannot be silently enrolled',async()=>{const f=setup();try{const files=[file()],p=await f.importer.preview({files});await assert.rejects(f.importer.commit({files,fingerprint:'changed',eligible:true,confirmed:true}),/Preview/);const old=file();old.text=old.text.replace(/20\d\d-\d\d-\d\dT[^,]+/,'2020-01-01T00:00:00Z');assert.match((await f.importer.preview({files:[old]})).rows[0].status,/48 hours/);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM cf_solo_sources').get().n,0);}finally{f.sql.close()}});
import {soloRepository} from '../server/solo-desk-repository.mjs';
import {signalInbound,signalOutbound} from '../server/sms-signal-service.mjs';
test('real priority projection remains incomplete after RAW; CONTROL has no projection or priority queue',async()=>{const f=fixture();try{const repo=soloRepository(f.repo.db,f.repo.scope),imp=rawImporter(repo,env),files=Array.from({length:6},(_,i)=>file(String(2000+i),'20255502'+String(i+10))),p=await imp.preview({files});const r=await imp.commit({files,fingerprint:p.fingerprint,eligible:true,confirmed:true});assert.equal(r.imported,6);assert.ok(r.results.every(x=>!x.warning),JSON.stringify(r));for(const row of r.results){const detail=await repo.detail(row.opportunity_id);if(row.cohort==='CONTROL'){assert.equal(detail.opportunityPriority,null);assert.equal(detail.possessionQuality,null);assert.equal(detail.nextBestAction,null);}else{assert.ok(detail.opportunityPriority);assert.notEqual(detail.opportunityPriority.score,100);}}}finally{f.sql.close()}});
test('RAW facts feed SIGNAL zero-repeat without enrollment creating a reply; CONTROL stays isolated',async()=>{const f=setup();try{let key;for(let n=0;n<100;n++)if((await pilotAssignment('awl:'+n)).cohort==='SIGNAL'){key=String(n);break;}const files=[file(key)],p=await f.importer.preview({files}),r=await f.importer.commit({files,fingerprint:p.fingerprint,eligible:true,confirmed:true});const record=await f.pilot.get(r.results[0].opportunity_id);const values=new Map(),store={get:async k=>values.get(k)||null,setJSON:async(k,v)=>values.set(k,v)},e={...env,COVERAGEFIT_DB:f.repo.db,COVERAGEFIT_SOLO_WORKSPACE_ID:'qa',CF_SMS_SIGNAL_ENABLED:'1',CF_SMS_SIGNAL_PILOT_ONLY:'1'};const now=new Date().toISOString();const c={id:record.conversation_id,contactPhone:'+12025550199',businessPhone:env.RINGCENTRAL_FROM_NUMBER,transcript:[{id:'out',direction:'outbound',body:'Is this for auto, home, or both?',occurredAt:now}]};const next=await signalInbound(c,{messageId:'new-reply',body:'Auto',occurredAt:now},{env:e,store});assert.equal(next.signal.facts.current_carrier,'Mercury');assert.equal(next.signal.facts.line,'AUTO');assert.equal(next.signal.decision_2,'ASK_ONE_QUESTION');assert.equal(next.signal.draft_status,'pending');assert.ok(!/who are you|auto, home|renewing soon/i.test(next.signal.reply),next.signal.reply);assert.equal((await signalOutbound({...c,id:'unenrolled'},{messageId:'out2',body:'Is this for auto, home, or both?',occurredAt:now},{env:e,store})).matched,false);const held=await signalInbound({...c,id:'unenrolled'},{messageId:'reply2',body:'Auto',occurredAt:now},{env:e,store});assert.equal(held.signal.reply,'');assert.equal(held.signal.pilot_cohort,'UNENROLLED');}finally{f.sql.close()}});
