import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {randomUUID} from 'node:crypto';import {readFileSync,readdirSync} from 'node:fs';
import {districtPilot,pilotAssignment,PILOT_FLAGS,pilotSummary,pilotCSV} from '../server/district-pilot.mjs';
import {pilotReconciliation} from '../server/pilot-reconciliation.mjs';
import {renderPilotAnalytics} from '../assets/js/pilot-analytics.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const db={prepare(q){let args=[];const stmt={bind(...v){args=v;return stmt},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}};return stmt},async batch(stmts){sql.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};const now=new Date().toISOString();for(const id of ['one','two'])sql.prepare('INSERT INTO cf_solo_opportunities(id,workspace_id,owner_id,contact_json,source,last_mutation_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,'qa','qa','{}','district','qa',now,now);const repo={db,scope:{workspace:'qa',actor:'qa'},sql:(q,...v)=>db.prepare(q).bind(...v),rows:async(q,...v)=>(await db.prepare(q).bind(...v).all()).results,own:async id=>{const r=sql.prepare('SELECT * FROM cf_solo_opportunities WHERE workspace_id=? AND id=?').get('qa',id);if(!r)throw new Error('unavailable');return r;}};return {sql,repo,pilot:districtPilot(repo),received:new Date(Date.now()-60000).toISOString()};}

async function setup(){const f=fixture();for(const [id,cohort] of [['one','CONTROL'],['two','SIGNAL']]){let key;for(let i=0;i<30;i++){key='measure:'+cohort+i;if((await pilotAssignment(key)).cohort===cohort)break;}await f.pilot.enroll({id,lead_key:key,eligible:true,received_at:f.received},randomUUID());}f.m=pilotReconciliation(f.repo);return f;}
const observations={useful_conversation:false,quote_ready:false,quote:false,bind:false,future_intent:false};
async function reconcile(f,rows){const p=await f.m.preview({rows});return f.m.apply({rows,fingerprint:p.fingerprint,confirmed:true},randomUUID());}
test('view/report never count calls; confirmed actual call is idempotent and cohort-scoped',async()=>{const f=await setup();try{await f.pilot.report();assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM cf_solo_activity WHERE kind='pilot_call_attempt'").get().n,0);await assert.rejects(f.m.call({id:'one'},randomUUID()));const rid=randomUUID();const r=await f.m.call({id:'one',confirmed:true},rid);await f.m.call({id:'one',confirmed:true},rid);assert.equal(r.cohort,'CONTROL');assert.equal(r.source,'producer confirmed');assert.equal(r.duration_seconds,null);await assert.rejects(f.m.call({id:'two',confirmed:true},rid));await assert.rejects(f.m.call({id:'not-owned',confirmed:true},randomUUID()));const records=(await f.pilot.report()).records;assert.equal(records.find(x=>x.opportunity_id==='one').call_attempts,1);assert.equal(records.find(x=>x.opportunity_id==='two').call_attempts,null);assert.equal(records[0].calls_complete,false);}finally{f.sql.close()}});
test('silent batch stays unknown until explicit no-work/no-call confirmation; no individual opens',async()=>{const f=await setup();try{await reconcile(f,['one','two'].map(id=>({id,outcomes:observations})));let r=await f.pilot.report();assert.ok(r.records.every(x=>x.producer_minutes===null&&x.call_attempts===null));const rows=['one','two'].map(id=>({id,measure:{effort_mode:'zero',calls_mode:'zero'},outcomes:observations}));const p=await f.m.preview({rows});assert.ok((await f.pilot.report()).records.every(x=>x.producer_minutes===null));const rid=randomUUID(),v={rows,fingerprint:p.fingerprint,confirmed:true};assert.equal((await f.m.apply(v,rid)).saved,2);assert.equal((await f.m.apply(v,rid)).saved,2);r=await f.pilot.report();assert.ok(r.records.every(x=>x.producer_minutes===0&&x.calls_complete));assert.ok(r.summary.every(x=>x.minutes_per_useful_conversation===null));assert.ok(r.summary.every(x=>x.quote_per_100_leads===0));}finally{f.sql.close()}});
test('new call invalidates preview and completeness; zero cannot erase activity',async()=>{const f=await setup();try{const rows=[{id:'two',measure:{effort_mode:'zero',calls_mode:'zero'},outcomes:observations}],p=await f.m.preview({rows});await f.m.call({id:'two',confirmed:true},randomUUID());await assert.rejects(f.m.apply({rows,fingerprint:p.fingerprint,confirmed:true},randomUUID()));await assert.rejects(f.m.preview({rows}),/Zero effort/);await reconcile(f,[{id:'two',measure:{effort_mode:'total',producer_minutes:3,calls_mode:'recorded'},outcomes:observations}]);let r=(await f.pilot.report()).records.find(x=>x.opportunity_id==='two');assert.equal(r.calls_complete,true);assert.equal(r.producer_minutes,3);await f.m.call({id:'two',confirmed:true},randomUUID());r=(await f.pilot.report()).records.find(x=>x.opportunity_id==='two');assert.equal(r.calls_complete,false);assert.equal(r.effort_complete,false);}finally{f.sql.close()}});
test('batch cannot erase positive outcomes, STOP or recorded effort; unknown premium preserved',async()=>{const f=await setup();try{await reconcile(f,[{id:'one',outcomes:{...observations,quote:true,bind:true,final_status:'WON'}}]);assert.equal((await f.pilot.report()).summary[0].bound_premium,null);await assert.rejects(f.m.preview({rows:[{id:'one',outcomes:{quote:false}}]}),/erase/);await reconcile(f,[{id:'two',outcomes:{stop:true,final_status:'STOP'}}]);await assert.rejects(f.m.preview({rows:[{id:'two',outcomes:{final_status:'OPEN'}}]}),/STOP/);await assert.rejects(f.m.preview({rows:[{id:'one',outcomes:{farmers_policy_count:1.5}}]}));}finally{f.sql.close()}});
test('complete economics use verified term premium; ratios null when review/calls/effort missing',()=>{const row={cohort:'SIGNAL',...observations,useful_conversation:true,quote_ready:true,quote:true,bind:true,bound_premium:1200,farmers_policy_count:2,producer_minutes:30,effort_complete:true,call_attempts:3,calls_complete:true,call_sources:['producer confirmed'],talk_minutes:null};const g=pilotSummary([row])[1];assert.equal(g.minutes_per_useful_conversation,30);assert.equal(g.calls_per_useful_conversation,3);assert.equal(g.calls_per_quote,3);assert.equal(g.premium_per_call,400);assert.equal(g.premium_per_producer_hour,2400);assert.equal(g.quote_per_100_leads,100);assert.equal(g.farmers_policy_count,2);assert.equal(g.talk_minutes,null);assert.equal(g.premium_per_talk_hour,null);for(const patch of [{calls_complete:false},{call_attempts:null}])assert.equal(pilotSummary([{...row,...patch}])[1].premium_per_call,null);assert.equal(pilotSummary([row,{cohort:'SIGNAL',producer_minutes:null}])[1].minutes_per_quote,null);assert.equal(pilotSummary([{...row,bound_premium:undefined}])[1].bound_premium,null);assert.equal(pilotSummary([])[0].quote_per_100_leads,null);});
test('analytics separates historical context, guardrails, provenance and small samples without winner',()=>{const summary=pilotSummary([]),html=renderPilotAnalytics({summary});for(const text of ['EFFICIENCY GUARDRAIL','10 households','7/day','7.4','not pilot outcome data','Small bind/premium samples','Not measured','0 / 0 complete'])assert.ok(html.includes(text),text);assert.doesNotMatch(html,/SIGNAL WON|CONTROL WON|winner badge/);assert.equal(summary[0].enrolled,0);assert.ok(pilotCSV([]).includes('call_attempts'));});
test('snapshot rejects stale observation and refuses cross-workspace or unknown measurement',async()=>{const f=await setup();try{const rows=[{id:'one'}],p=await f.m.preview({rows});await reconcile(f,[{id:'one',outcomes:{quote_ready:true}}]);await assert.rejects(f.m.apply({rows,fingerprint:p.fingerprint,confirmed:true},randomUUID()),/Preview again/);await assert.rejects(f.m.preview({rows:[{id:'absent'}]}));await assert.rejects(f.m.preview({rows:[{id:'one',measure:{talk_minutes:5}}]}),/Unsupported/);}finally{f.sql.close()}});

test('later batch recorded review preserves previously reconciled external work instead of replacing it',async()=>{const f=await setup();try{await reconcile(f,[{id:'one',measure:{effort_mode:'total',producer_minutes:10,calls_mode:'total',call_attempts:4},outcomes:observations}]);await f.m.call({id:'one',confirmed:true},randomUUID());await reconcile(f,[{id:'one',measure:{effort_mode:'recorded',calls_mode:'recorded'}}]);let r=(await f.pilot.report()).records.find(r=>r.opportunity_id==='one');assert.equal(r.producer_minutes,10);assert.equal(r.call_attempts,5);await assert.rejects(f.m.preview({rows:[{id:'one',measure:{effort_mode:'total',producer_minutes:2}}]}),/less than recorded/);}finally{f.sql.close()}});
