import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import {randomUUID} from 'node:crypto';
import {districtPilot} from '../server/district-pilot.mjs';
import {soloRepository} from '../server/solo-desk-repository.mjs';
import {producerWorkspace,classifyPopulation,attentionRank} from '../server/producer-workspace.mjs';
import {smsPanel} from '../assets/js/producer-sms.mjs';
import {createSmsConversationStore} from '../server/d1-json-store.mjs';
import {handleSmsSignal} from '../server/sms-signal-api.mjs';
import {handleSoloDesk} from '../server/solo-desk-api.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const db={prepare(q){let args=[];const stmt={bind(...v){args=v;return stmt},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}};return stmt},async batch(stmts){sql.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};const now=new Date().toISOString();for(const id of ['one','two'])sql.prepare('INSERT INTO cf_solo_opportunities(id,workspace_id,owner_id,contact_json,source,last_mutation_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,'qa','qa','{}','district','qa',now,now);const repo={db,scope:{workspace:'qa',actor:'qa'},sql:(q,...v)=>db.prepare(q).bind(...v),rows:async(q,...v)=>(await db.prepare(q).bind(...v).all()).results,own:async id=>{const r=sql.prepare('SELECT * FROM cf_solo_opportunities WHERE workspace_id=? AND id=?').get('qa',id);if(!r)throw new Error('unavailable');return r;}};return {sql,repo,pilot:districtPilot(repo),received:new Date(Date.now()-60000).toISOString()};}
function prepared(){const f=fixture();f.repo=soloRepository(f.repo.db,{workspace:'qa',actor:'qa'});f.env={COVERAGEFIT_DB:f.repo.db,COVERAGEFIT_SOLO_WORKSPACE_ID:'qa',COVERAGEFIT_PRODUCER_ACCESS_TOKEN:'synthetic-producer-key-for-tests',CF_SMS_SIGNAL_ENABLED:'1'};f.store=createSmsConversationStore(f.repo.db);f.work=producerWorkspace(f.repo,f.env);return f;}
const cid='sms-live-'+'a'.repeat(32),otherCid='sms-live-'+'b'.repeat(32);
function source(f,id,kind,value){f.sql.prepare('INSERT INTO cf_solo_sources(workspace_id,kind,source_id,opportunity_id,summary_json,updated_at) VALUES(?,?,?,?,?,?)').run('qa',kind,kind+'-'+id,id,JSON.stringify(value),new Date().toISOString());}
const pilot=(cohort,conversation_id=cid)=>({pilot_id:'SIGNAL_DISTRICT_PILOT_1',cohort,pilot_phase:'NEW_LEAD',conversation_id});
const signal=()=>({managed:true,revision:1,latest_inbound:'Auto',previous_outbound:'Auto, home, or both?',decision_2:'ASK_ONE_QUESTION',reply:'When does your policy renew?',draft_status:'pending',priority:'MEDIUM',az_inferred_stage:'CONTACT_ATTEMPT',az_recommended_stage:'ENGAGED',az_sync_status:'pending',facts:{line:'AUTO'}});
test('population follows explicit sources, never score/stage/SMS; synthetic pilot stays OTHER',()=>{assert.equal(classifyPopulation([]).population,'OTHER');assert.equal(classifyPopulation([{kind:'lead',summary:{context:{signalHome:{}}}}]).population,'WEB_DIRECT');assert.equal(classifyPopulation([{kind:'lead',summary:{rawFacts:{line:'AUTO'}}}]).population,'OTHER');assert.equal(classifyPopulation([{kind:'district_pilot_v1',summary:pilot('CONTROL')},{kind:'lead',summary:{permission:{}}}]).population,'DISTRICT_CONTROL');assert.equal(classifyPopulation([{kind:'district_pilot_v1',summary:{...pilot('SIGNAL'),pilot_phase:'TEST'}}]).population,'OTHER');});
test('work counts, population filters, global search and durable classification stay aligned',async()=>{const f=prepared();try{source(f,'one','district_pilot_v1',pilot('SIGNAL'));source(f,'two','district_pilot_v1',pilot('CONTROL',otherCid));f.sql.prepare('UPDATE cf_solo_opportunities SET contact_json=? WHERE id=?').run(JSON.stringify({name:'Find me'}),'two');let r=await f.work.list(new URLSearchParams());assert.equal(r.records.length,1);assert.equal(r.records[0].id,'one');assert.equal(r.counts.DISTRICT_CONTROL,1);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM cf_solo_sources WHERE kind='producer_population_v2'").get().n,2);r=await f.work.list(new URLSearchParams({population:'DISTRICT_SIGNAL',q:'Find me'}));assert.equal(r.records[0].population,'DISTRICT_CONTROL');assert.equal(r.records[0].priority,null);assert.equal(r.records[0].sms,null);f.sql.prepare("UPDATE cf_solo_opportunities SET stage='decision' WHERE id='two'").run();assert.equal((await f.work.detail('two')).population.population,'DISTRICT_CONTROL');}finally{f.sql.close()}});
test('detail returns exact SIGNAL context; CONTROL, WEB and OTHER have no embedded draft/pilot contamination',async()=>{const f=prepared();try{source(f,'one','district_pilot_v1',pilot('SIGNAL'));source(f,'two','district_pilot_v1',pilot('CONTROL',otherCid));await f.store.setJSON('sms-live-conversations/'+cid,{id:cid,signal:signal(),transcript:[]});await f.store.setJSON('sms-live-conversations/'+otherCid,{id:otherCid,signal:signal(),transcript:[]});const a=await f.work.detail('one'),b=await f.work.detail('two');assert.equal(a.sms.reply,signal().reply);assert.equal(b.sms,null);assert.equal(b.opportunityPriority,null);assert.equal(b.nextBestAction,null);assert.equal(smsPanel(b),'');f.sql.prepare("DELETE FROM cf_solo_sources WHERE opportunity_id='two'").run();source(f,'two','lead',{permission:{basis:'Contact requested'},context:{signalHome:{}}});const web=await f.work.detail('two');assert.equal(web.population.population,'WEB_DIRECT');assert.equal(web.pilot,null);assert.equal(web.sms,null);assert.equal(smsPanel(web),'');await assert.rejects(f.work.detail('other-workspace'));}finally{f.sql.close()}});
test('explicit call outranks a complete high score; stop cannot become attention bait',()=>{assert.ok(attentionRank({sms:{decision_2:'CALL'},priority:null})>attentionRank({priority:{queue:'shoot_now',score:100}}));assert.equal(attentionRank({sms:{decision_2:'STOP',priority:'URGENT',human_required:true,latest_inbound:'STOP'}}),0);});
test('embedded presentation withholds send on STOP, disabled processing and takeover; escapes replies',()=>{const d={population:{population:'DISTRICT_SIGNAL'},sms_enabled:true,sms:{...signal(),latest_inbound:'<script>bad</script>'}};assert.ok(smsPanel(d).includes('Approve &amp; send'));assert.ok(!smsPanel(d).includes('<script>'));assert.ok(!smsPanel({...d,sms:{...d.sms,decision_2:'STOP'}}).includes('data-sms-action="approve_send"'));assert.match(smsPanel({...d,sms_enabled:false}),/data-sms-action="approve_send" disabled/);assert.match(smsPanel({...d,sms:{...d.sms,human_active:true}}),/data-sms-action="approve_send" disabled/);});
test('embedded actions reuse canonical revision, identity, CONTROL and send-once guards',async()=>{const f=prepared();try{source(f,'one','district_pilot_v1',pilot('SIGNAL'));source(f,'two','district_pilot_v1',pilot('CONTROL',otherCid));await f.store.setJSON('sms-live-conversations/'+cid,{id:cid,contactPhone:'+12025550199',signal:signal(),transcript:[]});let sent=0;const post=b=>handleSmsSignal(new Request('https://coveragefit.test/api/sms/signal',{method:'POST',headers:{Authorization:'Bearer '+f.env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN,Origin:'https://coveragefit.test','Content-Type':'application/json'},body:JSON.stringify(b)}),{env:f.env,store:f.store,sendSignal:async()=>{sent++;return {providerMessageId:'synthetic-sent'}}});assert.equal((await post({opportunity_id:'two',conversation_id:cid,action:'approve_send',revision:1})).status,409);assert.equal((await post({opportunity_id:'one',conversation_id:otherCid,action:'edit',message:'Test',revision:1})).status,409);assert.equal((await post({opportunity_id:'one',conversation_id:cid,action:'edit',message:'Is next month right?',revision:1})).status,200);assert.equal(sent,0);assert.equal((await post({opportunity_id:'one',conversation_id:cid,action:'approve_send',revision:1})).status,409);assert.equal((await post({opportunity_id:'one',conversation_id:cid,action:'approve_send',revision:2})).status,200);assert.equal(sent,1);assert.equal((await post({opportunity_id:'one',conversation_id:cid,action:'approve_send',revision:2})).status,409);assert.equal(sent,1);assert.equal((await post({opportunity_id:'one',conversation_id:cid,action:'mark_az_updated',revision:3,stage:'ENGAGED'})).status,200);}finally{f.sql.close()}});
test('producer aggregate remains authenticated; legacy deep-link shell retains active controls',async()=>{const f=prepared();try{const r=await handleSoloDesk({request:new Request('https://coveragefit.test/api/solo-desk/producer-work'),env:f.env});assert.equal(r.status,401);const html=readFileSync(new URL('../agent/workspace/index.html',import.meta.url),'utf8');for(const area of ['work','import','analytics','tools'])assert.ok(html.includes('data-area="'+area+'"'));assert.ok(!html.includes('id="deskAcq"'));const legacy=readFileSync(new URL('../agent/workspace/legacy.html',import.meta.url),'utf8');assert.ok(legacy.includes('id="workspaceViewConsultation"'));assert.ok(legacy.includes('/assets/js/agent-workspace.js'));assert.ok(legacy.includes('/agent/workspace/workspace.css'));}finally{f.sql.close()}});
test('CONTROL stale Signal state is absent from Operations as well as Work',async()=>{const f=prepared();try{source(f,'one','district_pilot_v1',pilot('CONTROL'));await f.store.setJSON('sms-live-conversations/'+cid,{id:cid,contactPhone:'+12025550199',signal:signal()});const r=await handleSmsSignal(new Request('https://coveragefit.test/api/sms/signal',{headers:{Authorization:'Bearer '+f.env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN}}),{env:f.env,store:f.store});assert.equal(r.status,200);assert.equal((await r.json()).conversations.length,0);}finally{f.sql.close()}});
test('optional compact outcome fields retain validation and atomic effort saving',async()=>{const f=prepared();try{const p=districtPilot(f.repo,f.env);await p.enroll({id:'one',lead_key:'qa:advanced',received_at:f.received,eligible:true},randomUUID());const v={id:'one',version:1,minutes:5,effort_category:'discovery',quote:false,bind:false,useful_conversation:true,final_status:'OPEN',confirmed:true,extra_flags:{sales_positive:true,quote_sent:true}};await assert.rejects(p.quickReview(v,randomUUID()),/prepared quote/);assert.equal((await p.get('one')).version,1);const saved=await p.quickReview({...v,quote:true},randomUUID());assert.equal(saved.observation.quote_sent,true);assert.equal(f.sql.prepare('SELECT category FROM cf_opportunity_effort').get().category,'discovery');}finally{f.sql.close()}});


test('normal web work wrap renders saved ISO due dates without breaking the detail',async()=>{
 const {mountWorkWrap}=await import('../assets/js/producer-work-wrap.mjs');
 const nodes=new Map();const root={innerHTML:'',addEventListener(){},querySelector(key){if(!nodes.has(key))nodes.set(key,{});return nodes.get(key)}};
 mountWorkWrap(root,{opportunity:{id:'web',status:'open',stage:'inquiry'},tasks:[{id:'task',due_at:'2026-09-25T17:30:00.000Z',title:'Call as requested'}]},()=>{},()=>{});
 assert.match(root.innerHTML,/value="2026-09-25T10:30"/);
 assert.match(root.innerHTML,/Save work/);
 assert.doesNotMatch(root.innerHTML,/Approve &amp; send|DISTRICT_SIGNAL/);
});

test('same opportunity reload returns newest inbound, facts, draft revision and stage',async()=>{const f=prepared();try{source(f,'one','district_pilot_v1',pilot('SIGNAL'));await f.store.setJSON('sms-live-conversations/'+cid,{id:cid,signal:signal(),transcript:[]});const first=await f.work.detail('one');const latest={...signal(),revision:4,latest_inbound:'Under $220',facts:{line:'AUTO',price_target:220},decision_2:'CALL',reply:'',draft_status:'none',az_recommended_stage:'QUOTE_READY'};await f.store.setJSON('sms-live-conversations/'+cid,{id:cid,signal:latest,transcript:[]});const next=await f.work.detail('one');assert.equal(first.sms.revision,1);assert.equal(next.sms.revision,4);assert.equal(next.sms.latest_inbound,'Under $220');assert.equal(next.sms.facts.price_target,220);assert.equal(next.sms.az_recommended_stage,'QUOTE_READY');assert.ok(smsPanel(next).includes('Revision 4'));}finally{f.sql.close()}});
test('Work shows pending SMS without inventing opportunities; enrollment removes pending label',async()=>{const f=prepared();try{await f.store.setJSON('sms-live-conversations/'+cid,{id:cid,contactPhone:'+12025550199',lastInboundAt:new Date().toISOString(),transcript:[{direction:'outbound',body:'Is this for auto, home, or both?'},{direction:'inbound',body:'Home'}]});const work=producerWorkspace(f.repo,f.env),pending=await work.pendingSms();assert.equal(pending.records.length,1);assert.match(pending.records[0].label,/AgencyZoom lead/);assert.equal(pending.records[0].latest_inbound,'Home');assert.equal(f.sql.prepare('SELECT count(*) n FROM cf_solo_opportunities').get().n,2);source(f,'one','district_pilot_v1',pilot('CONTROL'));assert.equal((await work.pendingSms()).records.length,0);}finally{f.sql.close()}});

test('Work list exposes creation separately from updated activity',async()=>{const f=prepared();try{
 f.sql.prepare('UPDATE cf_solo_opportunities SET created_at=?,updated_at=? WHERE id=?').run('2026-09-20T17:00:00Z','2026-09-26T19:00:00Z','one');
 const result=await f.work.list(new URLSearchParams({population:'ALL',status:'all'}));const row=result.records.find(r=>r.id==='one');
 assert.equal(row.created_at,'2026-09-20T17:00:00Z');assert.equal(row.updated_at,'2026-09-26T19:00:00Z');assert.equal(row.received_at,null);
}finally{f.sql.close();}});
