import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {soloRepository} from '../server/solo-desk-repository.mjs';
import {districtPilot} from '../server/district-pilot.mjs';
import {createSmsConversationStore} from '../server/d1-json-store.mjs';
import {signalContinue} from '../server/signal-continue-service.mjs';
import * as core from '../server/signal-continue-core.mjs';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const db={prepare(q){let args=[];const stmt={bind(...v){args=v;return stmt},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {meta:sql.prepare(q).run(...args)}}};return stmt},async batch(stmts){sql.exec('BEGIN');try{const result=[];for(const s of stmts)result.push(await s.run());sql.exec('COMMIT');return result}catch(e){sql.exec('ROLLBACK');throw e}}};const now=new Date().toISOString();for(const id of ['one','two'])sql.prepare('INSERT INTO cf_solo_opportunities(id,workspace_id,owner_id,contact_json,source,last_mutation_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,'qa','qa','{}','district','qa',now,now);const repo={db,scope:{workspace:'qa',actor:'qa'},sql:(q,...v)=>db.prepare(q).bind(...v),rows:async(q,...v)=>(await db.prepare(q).bind(...v).all()).results,own:async id=>{const r=sql.prepare('SELECT * FROM cf_solo_opportunities WHERE workspace_id=? AND id=?').get('qa',id);if(!r)throw new Error('unavailable');return r;}};return {sql,repo,pilot:districtPilot(repo),received:new Date(Date.now()-60000).toISOString()};}

const at='2026-09-26T12:00:00.000Z';
async function setup(cohort='SIGNAL'){
 const f=fixture();f.repo=soloRepository(f.repo.db,{workspace:'qa',actor:'qa'});f.env={COVERAGEFIT_DB:f.repo.db,COVERAGEFIT_SOLO_WORKSPACE_ID:'qa'};f.store=createSmsConversationStore(f.repo.db);f.sent=0;
 f.pilot={opportunity_id:'one',received_at:at,pilot_id:'SIGNAL_DISTRICT_PILOT_1',cohort,pilot_phase:'NEW_LEAD',conversation_id:'thread',raw_facts:{line:'AUTO',current_carrier:'Mercury',renewal_date:'2026-10-16',vehicle:'Subaru Ascent'}};
 f.sql.prepare('INSERT INTO cf_solo_sources(workspace_id,kind,source_id,opportunity_id,summary_json,updated_at) VALUES(?,?,?,?,?,?)').run('qa','district_pilot_v1','pilot','one',JSON.stringify(f.pilot),at);
 await f.store.setJSON('sms-live-conversations/thread',{id:'thread',contactPhone:'+12025550199',signal:{revision:1,facts:{},decision_2:'ASK_ONE_QUESTION',priority:'MEDIUM'}});
 f.service=signalContinue(f.repo,f.env,{now:at,send:async()=>{f.sent++;return {providerMessageId:'fake-provider'};}});return f;
}
const selection={id:'one',trigger:'busy',interestConfirmed:true,producerChosen:true};
async function start(f){const d=await f.service.create(selection);const token=d.draft.match(/\/s\/([A-Za-z0-9_-]+)/)[1];await f.service.producer({id:'one',revision:1,action:'approve_send'});return {token,state:await f.service.resume(token)};}
test('unguessable scoped token contract: hash-only lookup, fixed production URL, expiry/revocation',async()=>{const a=core.newContinueToken(),b=core.newContinueToken();assert.notEqual(a,b);assert.equal(a.length,43);assert.equal((await core.continueKey(a)).includes(a),false);assert.equal(core.continueUrl(a),'https://coveragefit.com/s/'+a);assert.equal(await core.continueKey('opp_name_phone'),null);assert.equal(core.validContinueSession({scope:core.CONTINUE_KIND,expires_at:'2026-09-27'},Date.parse(at)),true);assert.equal(core.validContinueSession({scope:'other',expires_at:'2026-09-27'},Date.parse(at)),false);assert.equal(core.validContinueSession({scope:core.CONTINUE_KIND,expires_at:at},Date.parse(at)),false);});
test('CONTROL denied in service, no token created',async()=>{const f=await setup('CONTROL');try{await assert.rejects(f.service.create(selection),/CONTROL/);assert.equal(f.sql.prepare('SELECT count(*) n FROM sms_handoffs').get().n,0);}finally{f.sql.close();}});
test('primary trigger does not replace callback, future timing, urgent action or unknown owner',()=>{const v={population:'DISTRICT_SIGNAL',owner:'DISTRICT_SIGNAL',facts:{line:'AUTO'},signal:{},...selection};assert.equal(core.continueEligibility(v).eligible,true);for(const patch of [{owner:'UNKNOWN'},{facts:{line:'AUTO',callback_date:'2026-09-26'}},{signal:{decision_2:'LATER'}},{signal:{decision_2:'CALL'}},{signal:{priority:'URGENT'}},{trigger:'later'},{interestConfirmed:false}])assert.equal(core.continueEligibility({...v,...patch}).eligible,false);assert.equal(core.continueEligibility({...v,population:'WEB_DIRECT',owner:'FIRST_PARTY_408',activeFirstParty:true}).eligible,false);});
test('known RAW fields are never requested; two submitted answers early-stop on same opportunity',async()=>{const f=await setup();try{const {token,state}=await start(f);assert.equal(state.question.id,'auto_trigger');assert.equal(f.sent,1);const a=await f.service.answer(token,{revision:state.revision,question_id:state.question.id,code:'renewal_price'});assert.equal(a.question.id,'auto_shopping_intent');const b=await f.service.answer(token,{revision:a.revision,question_id:a.question.id,code:'ready_now'});assert.equal(b.done,true);assert.equal(f.sql.prepare('SELECT count(*) n FROM cf_solo_opportunities').get().n,2);const summary=JSON.parse(f.sql.prepare("SELECT summary_json FROM cf_solo_sources WHERE kind='signal_continue_v1'").get().summary_json);assert.equal(summary.decision_2,'CALL');assert.equal(summary.priority,'HIGH');assert.equal(summary.answers.length,2);assert.equal(summary.provenance.shoppingIntent.source,'signal_continue');assert.equal(f.sent,1);assert.equal((await f.service.resume(token)).done,true);}finally{f.sql.close();}});
test('creation/edit do not send; stale approval and repeat approval denied',async()=>{const f=await setup();try{const d=await f.service.create(selection);assert.equal(f.sent,0);await f.service.producer({id:'one',revision:1,action:'edit',message:d.draft});assert.equal(f.sent,0);await assert.rejects(f.service.producer({id:'one',revision:1,action:'approve_send'}));await f.service.producer({id:'one',revision:2,action:'approve_send'});await assert.rejects(f.service.producer({id:'one',revision:2,action:'approve_send'}));assert.equal(f.sent,1);await assert.rejects(f.service.producer({id:'two',revision:3,action:'approve_send'}));}finally{f.sql.close();}});
test('abandonment preserves actual answer and resume does not restart',async()=>{const f=await setup();try{const {token,state}=await start(f);await f.service.answer(token,{revision:state.revision,question_id:state.question.id,code:'just_comparing'});const resumed=await f.service.resume(token);assert.equal(resumed.question.id,'auto_shopping_intent');assert.equal(f.sent,1);await assert.rejects(f.service.answer(token,{revision:state.revision,question_id:state.question.id,code:'just_comparing'}));}finally{f.sql.close();}});
for(const [action,expected] of [['urgent','CALL'],['call','CALL'],['quote','CALL'],['later','LATER'],['negative','CLOSE'],['stop','STOP']])test('explicit '+action+' interrupts check-in',async()=>{const f=await setup();try{const {token,state}=await start(f);const r=await f.service.answer(token,{revision:state.revision,action,...(action==='later'?{future_date:'2027-02-01'}:{})});assert.equal(r.done,true);const c=await f.store.get('sms-live-conversations/thread');assert.equal(c.signal.decision_2,expected);assert.equal(c.signal.reply,'');assert.equal(f.sent,1);if(action==='stop')assert.equal(c.smsConsent.status,'opted_out');if(action==='later')assert.equal(c.signal.future_date,'2027-02-01');}finally{f.sql.close();}});
test('future/research exits without CALL and ceiling does not generate another question',()=>{assert.equal(core.continueStep({product:'auto',autoNeed:'just_comparing',shoppingIntent:'researching',decisionTiming:'future'}).decision_2,'LATER');assert.equal(core.continueStep({product:'auto'},6).done,true);assert.equal(core.continueStep({product:'home',reviewReason:'nonrenewal_notice'}).priority,'URGENT');});
test('token expiry, revoke, malformed token and unapproved token all fail safely',async()=>{const f=await setup();try{const d=await f.service.create(selection),token=d.draft.match(/\/s\/([A-Za-z0-9_-]+)/)[1];await assert.rejects(f.service.resume(token),/not available yet/);await assert.rejects(f.service.resume('not-a-token'));const later=signalContinue(f.repo,f.env,{now:'2026-10-04T12:00:00Z'});await assert.rejects(later.resume(token),/expired/);await f.service.producer({id:'one',revision:1,action:'revoke'});await assert.rejects(f.service.resume(token),/expired/);}finally{f.sql.close();}});
test('new inbound invalidates stale answer and routes current explicit CALL on resume',async()=>{const f=await setup();try{const {token,state}=await start(f);const c=await f.store.get('sms-live-conversations/thread');c.signal.revision++;c.signal.decision_2='CALL';await f.store.setJSON('sms-live-conversations/thread',c);await assert.rejects(f.service.answer(token,{revision:state.revision,question_id:state.question.id,code:'renewal_price'}),/New conversation/);assert.equal((await f.service.resume(token)).done,true);}finally{f.sql.close();}});
test('external STOP immediately invalidates continuation',async()=>{const f=await setup();try{const {token}=await start(f);const c=await f.store.get('sms-live-conversations/thread');c.smsConsent={status:'opted_out'};await f.store.setJSON('sms-live-conversations/thread',c);await assert.rejects(f.service.resume(token),/no longer available/);}finally{f.sql.close();}});
test('uncertain send cannot be retried; initial create idempotently refuses a second active link',async()=>{const f=await setup();try{await f.service.create(selection);await assert.rejects(f.service.create(selection),/existing check-in/);const broken=signalContinue(f.repo,f.env,{now:at,send:async()=>{throw Error('provider timeout')}});await assert.rejects(broken.producer({id:'one',revision:1,action:'approve_send'}),/uncertain/);await assert.rejects(broken.producer({id:'one',revision:2,action:'approve_send'}),/delivery review/);}finally{f.sql.close();}});
test('active session pauses qualification and does not fabricate RAW intent',async()=>{const f=await setup();try{const {token}=await start(f),c=await f.store.get('sms-live-conversations/thread');assert.equal(c.signal.continue_active,true);assert.equal(c.signal.reply,'');assert.equal(c.signal.draft_status,'none');assert.equal((await f.service.resume(token)).question.id,'auto_trigger');const output=JSON.stringify(await f.service.resume(token));for(const secret of ['Mercury','Subaru','opportunity','cohort','score','+1202'])assert.equal(output.includes(secret),false);}finally{f.sql.close();}});
test('known fresh SMS motivation is reused without repeating the reason question',async()=>{const f=await setup();try{const c=await f.store.get('sms-live-conversations/thread');c.signal.facts={shopping_reason:'price'};c.signal.response_timestamp=at;await f.store.setJSON('sms-live-conversations/thread',c);assert.equal((await f.service.preview('one')).step.question.id,'auto_shopping_intent');}finally{f.sql.close();}});
test('new facts refresh canonical priority without changing source RAW facts or creating another lead',async()=>{const f=await setup();try{const {token,state}=await start(f);const a=await f.service.answer(token,{revision:state.revision,question_id:state.question.id,code:'renewal_price'});await f.service.answer(token,{revision:a.revision,question_id:a.question.id,code:'ready_now'});const p=await f.repo.opportunityPriority('one');assert.ok(p);assert.equal(p.dimensions.intent.points<=30,true);assert.deepEqual(JSON.parse(f.sql.prepare("SELECT summary_json FROM cf_solo_sources WHERE kind='district_pilot_v1'").get().summary_json).raw_facts,f.pilot.raw_facts);assert.equal(f.sql.prepare("SELECT count(*) n FROM cf_solo_activity WHERE kind='signal_continue_answer'").get().n,2);}finally{f.sql.close();}});
test('public endpoint is feature gated, same-origin, bounded and non-disclosing',async()=>{const {onRequest}=await import('../functions/api/signal/continue.js');const f=await setup();try{const post=(env,body,origin='https://coveragefit.com')=>onRequest({env:{...f.env,...env},request:new Request('https://coveragefit.com/api/signal/continue',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'127.0.0.1'},body:JSON.stringify(body)})});assert.equal((await post({},{})).status,404);assert.equal((await post({SIGNAL_CONTINUE_ENABLED:'1'},{},'https://evil.example')).status,403);assert.equal((await post({SIGNAL_CONTINUE_ENABLED:'1'},{token:'bad',action:'resume'})).status,404);assert.equal((await post({SIGNAL_CONTINUE_ENABLED:'1'},{name:'forbidden'})).status,422);}finally{f.sql.close();}});
test('analytics keeps missing effort unknown and completion subtype descriptive',async()=>{const {continueAnalytics}=await import('../server/signal-continue-analytics.mjs');const f=await setup();try{const {token,state}=await start(f);await f.service.answer(token,{revision:state.revision,action:'later',future_date:'2027-02-01'});const a=await continueAnalytics(f.repo,f.env,new Date(at));assert.equal(a.links_sent,1);assert.equal(a.completions,1);assert.equal(a.later_after_completion,1);assert.equal(a.producer_minutes,null);assert.equal(a.minutes_per_useful_completion,null);assert.equal(a.delivered,null);assert.match(a.basis,/not randomized/);}finally{f.sql.close();}});
test('CONTROL preview offers no question or draft through hidden API paths',async()=>{const f=await setup('CONTROL');try{assert.equal((await f.service.preview('one')).step,null);assert.equal(await f.service.draft('one'),null);}finally{f.sql.close();}});
test('existing shared thread lock prevents concurrent create and answer mutations',async()=>{const f=await setup();try{await f.store.setJSON('sms-signal/locks/thread',{at},{onlyIfNew:true});await assert.rejects(f.service.create(selection),/processing/);assert.equal(f.sql.prepare('SELECT count(*) n FROM sms_handoffs').get().n,0);}finally{f.sql.close();}});
test('RAW historical intent never becomes fresh continuation intent',async()=>{const f=await setup();try{f.pilot.raw_facts.shopping_intent='actively comparing';f.sql.prepare("UPDATE cf_solo_sources SET summary_json=? WHERE kind='district_pilot_v1'").run(JSON.stringify(f.pilot));const {token,state}=await start(f);const next=await f.service.answer(token,{revision:state.revision,question_id:state.question.id,code:'renewal_price'});assert.equal(next.question.id,'auto_shopping_intent');}finally{f.sql.close();}});
