import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {handleSignalHomeHandoff,validateHomeRequest} from '../server/signal-home-handoff.mjs';
import {createPVXRecordStore} from '../server/d1-json-store.mjs';
const secret='synthetic-test-secret-not-a-real-credential';const env={COVERAGEFIT_LEAD_SYNC_SECRET:secret,SIGNAL_HOME_HANDOFF_ENABLED:'1'};
const fixture=()=>({version:'signal-home-contact-v1',sessionId:'synthetic-home-session-1234',name:'Synthetic QA',phone:'2025550123',mode:'text',permission:true,answers:[{questionId:'home_trigger',optionCode:'buying_home'},{questionId:'home_shopping_intent',optionCode:'ready_now'},{questionId:'home_decision_timing',optionCode:'within_14'}]});
function database(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const db={prepare(q){let args=[];const stmt={bind(...v){args=v;return stmt},async first(){return sql.prepare(q).get(...args)||null},async all(){return {results:sql.prepare(q).all(...args)}},async run(){return {success:true,meta:sql.prepare(q).run(...args)}}};return stmt},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,store:createPVXRecordStore(db)};}
function request(body,signature=true){const raw=JSON.stringify(body),at=String(Date.now());return new Request('https://coveragefit.test/api/signal/home-handoff',{method:'POST',body:raw,headers:{'content-type':'application/json','x-coveragefit-sent-at':at,'x-coveragefit-signature':signature?createHmac('sha256',secret).update(at+'.'+raw).digest('hex'):'bad'}});}
test('signed Home request reaches existing SQLite producer desk; repeat has one lead and opportunity',async()=>{const f=database();try{for(let i=0;i<2;i++){const r=await handleSignalHomeHandoff(request(fixture()),{...f,env});assert.ok(r.ok,await r.clone().text());assert.equal((await r.json()).operatorVisible,true);}assert.equal(f.sql.prepare('SELECT count(*) n FROM pvx_records').get().n,1);assert.equal(f.sql.prepare('SELECT count(*) n FROM cf_solo_opportunities').get().n,1);const record=JSON.parse(f.sql.prepare('SELECT data_json FROM pvx_records').get().data_json);assert.equal(record.context.decisionTiming,'within_14');assert.equal(record.context.signalHome.answers.length,3);assert.equal(record.consent.agencyContact.callPermitted,false);assert.equal(record.consent.agencyContact.personalTextPermitted,true);assert.equal(record.consent.automatedMarketingSms.granted,false);const source=JSON.parse(f.sql.prepare("SELECT summary_json FROM cf_solo_sources WHERE kind='lead'").get().summary_json);assert.equal(source.context.signalHome.answers[0].answer,'I am buying a home');}finally{f.sql.close()}});
test('permission, signature, timing and known option validation; immediate human path',async()=>{assert.throws(()=>validateHomeRequest({...fixture(),permission:false}));assert.throws(()=>validateHomeRequest({...fixture(),mode:'callback'}));assert.throws(()=>validateHomeRequest({...fixture(),answers:[{questionId:'home_trigger',optionCode:'invented'}]}));assert.equal(validateHomeRequest({...fixture(),answers:[]}).answers.length,0);assert.equal((await handleSignalHomeHandoff(request(fixture(),false),{env})).status,401);assert.equal((await handleSignalHomeHandoff(request(fixture()),{env:{}})).status,503)});
test('failed projection is not success; retry recovers saved request',async()=>{const f=database();try{const failed=await handleSignalHomeHandoff(request(fixture()),{...f,env,project:async()=>({ok:false})});assert.equal(failed.status,503);assert.equal((await failed.json()).saved,true);const retry=await handleSignalHomeHandoff(request(fixture()),{...f,env});assert.equal((await retry.json()).idempotent,true);}finally{f.sql.close()}});

test('concurrent duplicate deliveries converge without duplicate opportunities',async()=>{const f=database();try{await Promise.all(Array.from({length:8},()=>handleSignalHomeHandoff(request(fixture()),{...f,env})));const retry=await handleSignalHomeHandoff(request(fixture()),{...f,env});assert.ok(retry.ok);assert.equal(f.sql.prepare('SELECT count(*) n FROM pvx_records').get().n,1);assert.equal(f.sql.prepare('SELECT count(*) n FROM cf_solo_opportunities').get().n,1);}finally{f.sql.close()}});
