import {producerWorkspace} from '../server/producer-workspace.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';
import {soloRepository,identity} from '../server/solo-desk-repository.mjs';
import {createSmsConversationStore} from '../server/d1-json-store.mjs';
import {copilotService} from '../server/signal-copilot-service.mjs';
import {copilotContext,minimize} from '../server/signal-copilot-context.mjs';
import {validateReasoning} from '../server/signal-copilot-contract.mjs';
import {aiConfig,reasonWithProvider,safeProviderFailure} from '../server/ai-provider.mjs';
import {handleSmsSignal} from '../server/sms-signal-api.mjs';
import {handleSoloDesk} from '../server/solo-desk-api.mjs';
import {copilotPanel} from '../assets/js/producer-copilot.mjs';
const cid='sms-live-'+('a'.repeat(64)),key='sms-live-conversations/'+cid;
const result=()=>({interpretation:{summary:'Open to comparison',intent:1,urgency:0,engagement:1,shopping_reason:'comparison',objections:[]},fact_proposals:[],state_changes:[],missing_information:{highest_value_gap:'annual_mileage',other_useful_gaps:['vehicle_ownership'],why:'Useful quote input'},decision:{candidate:'ASK_ONE_QUESTION',why_now:'Mileage is missing'},reply:{draft:'About how many miles a year do you drive?',purpose:'Discover mileage',asks:['annual_mileage']},thread_summary_delta:'Open to comparison',ambiguities:[],human_review_required:true});
async function setup(){
 const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));
 const db={prepare(q){let a=[];const s={bind(...v){a=v;return s;},async first(){return sql.prepare(q).get(...a)||null;},async all(){return {results:sql.prepare(q).all(...a)};},async run(){return {meta:sql.prepare(q).run(...a)};}};return s;},async batch(stmts){sql.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 const env={COVERAGEFIT_DB:db,COVERAGEFIT_SOLO_WORKSPACE_ID:'qa',COVERAGEFIT_PRODUCER_ACCESS_TOKEN:'synthetic-producer-access-long-enough',CF_SMS_SIGNAL_ENABLED:'1',CF_SMS_SIGNAL_PILOT_ONLY:'1',CF_AI_ENABLED:'1',CF_SIGNAL_COPILOT_ENABLED:'1',OPENAI_API_KEY:'synthetic-only-key',CF_AI_MONTHLY_BUDGET_USD:'10',CF_AI_MODELS_JSON:JSON.stringify({NORMAL_REASON:{model:'fixture-model',input_per_million:.25,output_per_million:2}})};
 const repo=soloRepository(db,identity(env)),store=createSmsConversationStore(db),at=new Date().toISOString();
 sql.prepare('INSERT INTO cf_solo_opportunities(id,workspace_id,owner_id,contact_json,source,last_mutation_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('one','qa','qa','{}','district','test',at,at);
 const pilot={pilot_id:'SIGNAL_DISTRICT_PILOT_1',pilot_phase:'NEW_LEAD',cohort:'SIGNAL',conversation_id:cid};
 sql.prepare('INSERT INTO cf_solo_sources VALUES(?,?,?,?,?,?)').run('qa','district_pilot_v1','lead-one','one',JSON.stringify(pilot),at);
 const conversation={id:cid,contactPhone:'+12025550199',signal:{managed:true,revision:1,latest_inbound:'I have Allstate now and bought a 2026 Honda Ridgeline.',inbound_message_id:'in-1',decision_2:'ASK_ONE_QUESTION',reply:'What has you looking?',draft_status:'pending',facts:{current_carrier:'Allstate',vehicle:'2026 Honda Ridgeline'}},transcript:[{id:'in-1',direction:'inbound',body:'I have Allstate now and bought a 2026 Honda Ridgeline.',occurredAt:at}]};
 await store.setJSON(key,conversation);let calls=0;const provider=async()=>{calls++;return {result:result(),usage:{input_tokens:500,cached_input_tokens:0,output_tokens:200}};};
 const req=b=>new Request('https://example.test/api/sms/signal',{method:'POST',headers:{authorization:'Bearer '+env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN,origin:'https://example.test','content-type':'application/json'},body:JSON.stringify(b)});
 return {sql,db,env,repo,store,pilot,conversation,provider,req,calls:()=>calls,svc:copilotService(repo,env,{provider})};
}
test('mocked workflow generates, revises, selects, explicitly sends once and logs final message',async()=>{const f=await setup();try{
 const first=await f.svc.act({action:'analyze',id:'one'});assert.equal(f.calls(),1);assert.equal((await f.store.get(key)).signal.reply,'What has you looking?');
 const cached=await f.svc.act({action:'analyze',id:'one'});assert.equal(cached.cached,true);assert.equal(f.calls(),1);
 const revise= copilotService(f.repo,f.env,{provider:async(ctx)=>{assert.equal(ctx.producer_direction,'ask if financed too');const r=result();r.reply={draft:'About how many miles a year do you drive, and is it financed or owned outright?',purpose:'One discovery step',asks:['annual_mileage','vehicle_ownership']};return {result:r,usage:{input_tokens:600,cached_input_tokens:0,output_tokens:220}};}});
 const revised=await revise.act({action:'revise',id:'one',suggestion_id:first.suggestion.id,direction:'ask if financed too'});
 assert.equal((await f.store.get(key)).signal.facts.vehicle_ownership,undefined);
 let sends=0;const options={env:f.env,store:f.store,sendSignal:async()=>{sends++;return {providerMessageId:'mock-send'};}};
 const edit=await handleSmsSignal(f.req({action:'edit',opportunity_id:'one',conversation_id:cid,revision:1,copilot_id:revised.suggestion.id,message:revised.suggestion.result.reply.draft}),options);assert.equal(edit.status,200,await edit.clone().text());assert.equal(sends,0);
 const approval={action:'approve_send',opportunity_id:'one',conversation_id:cid,revision:2};assert.equal((await handleSmsSignal(f.req(approval),options)).status,200);assert.equal(sends,1);
 assert.equal((await handleSmsSignal(f.req(approval),options)).status,409);assert.equal(sends,1);
 const saved=await f.store.get('signal-copilot/qa/requests/'+revised.suggestion.id);assert.equal(saved.final_approved_message,revised.suggestion.result.reply.draft);assert.equal(saved.provider_message_id,'mock-send');assert.ok((await f.svc.metrics()).charged_or_reserved_usd>0);
 }finally{f.sql.close();}});
for(const mode of ['STOP','DNC','CONTROL','OTHER','WRONG_NUMBER','off'])test(mode+' blocks provider calls',async()=>{const f=await setup();try{
 if(mode==='CONTROL'||mode==='OTHER')f.sql.prepare('UPDATE cf_solo_sources SET summary_json=?').run(JSON.stringify({...f.pilot,cohort:mode}));
 else if(mode==='off')f.env.CF_AI_ENABLED='0';else{f.conversation.signal.latest_inbound=mode==='WRONG_NUMBER'?'Wrong number':mode;f.conversation.signal.contact_suppressed=mode==='DNC';await f.store.setJSON(key,f.conversation);}
 await assert.rejects(f.svc.act({action:'analyze',id:'one'}));assert.equal(f.calls(),0);
 }finally{f.sql.close();}});
for(const field of ['current_carrier','vehicle','renewal_date','shopping_reason','vehicle_ownership','annual_mileage'])test('ZERO-REPEAT holds known '+field,()=>{const r=result();r.reply.asks=[field];r.reply.draft='Could you confirm that?';const valid=validateReasoning(r,{messages:[],known_answers:{[field]:{status:'KNOWN',value:'known'}},do_not_reask:[field]});assert.equal(valid.reply.draft,'');assert.deepEqual(valid.validation.repeated_fields,[field]);});
test('uncertain facts remain eligible for confirmation; conflicts never overwrite facts',()=>{const r=result();r.fact_proposals=[{field:'current_carrier',value:'Allstate',confidence:.99,evidence_text:'Allstate',message_id:'in'}];r.reply.asks=['current_carrier'];const v=validateReasoning(r,{messages:[{id:'in',direction:'inbound',body:'Allstate'}],known_answers:{current_carrier:{value:'Mercury',status:'KNOWN'}},do_not_reask:[]});assert.equal(v.fact_proposals[0].status,'CONFLICTING');assert.ok(v.reply.draft);});
for(const mutation of [r=>r.decision.candidate='SEND',r=>r.interpretation.intent=4,r=>r.reply.draft='a'.repeat(701),r=>r.extra=true,r=>delete r.ambiguities,r=>r.fact_proposals=[{field:'income',value:'high',confidence:1,evidence_text:'high',message_id:'in'}]])test('schema rejects malformed or unauthorized output',()=>{const r=result();mutation(r);assert.throws(()=>validateReasoning(r,{messages:[],known_answers:{},do_not_reask:[]}));});
test('known matching fact proposal is ignored before evidence validation',()=>{const r=result();r.fact_proposals=[{field:'line',value:'AUTO',confidence:.99,evidence_text:'auto',message_id:'missing'}];const v=validateReasoning(r,{messages:[],known_answers:{line:{status:'KNOWN',value:'AUTO'}},do_not_reask:['line']});assert.deepEqual(v.fact_proposals,[]);});
test('boolean fact values normalize common yes/no forms to canonical strings',()=>{for(const [input,expected] of [['yes','true'],['YES','true'],['1','true'],['no','false'],['No','false'],['0','false']]){const r=result();r.fact_proposals=[{field:'currently_insured',value:input,confidence:.99,evidence_text:'insured',message_id:'in'}];const v=validateReasoning(r,{messages:[{id:'in',direction:'inbound',body:'I am insured now.'}],known_answers:{currently_insured:{status:'UNKNOWN',value:null}},do_not_reask:[]});assert.equal(v.fact_proposals[0].value,expected);}const bad=result();bad.fact_proposals=[{field:'currently_insured',value:'probably',confidence:.99,evidence_text:'insured',message_id:'in'}];assert.throws(()=>validateReasoning(bad,{messages:[{id:'in',direction:'inbound',body:'I am insured now.'}],known_answers:{currently_insured:{status:'UNKNOWN',value:null}},do_not_reask:[]}),/invalid_fact_value/);});
test('literal evidence matching is case and whitespace tolerant but still literal',()=>{const r=result();r.fact_proposals=[{field:'line',value:'AUTO',confidence:.99,evidence_text:'auto',message_id:'in'}];const v=validateReasoning(r,{messages:[{id:'in',direction:'inbound',body:'I am shopping for Auto insurance.'}],known_answers:{line:{status:'UNKNOWN',value:null}},do_not_reask:[]});assert.equal(v.fact_proposals[0].field,'line');assert.equal(v.fact_proposals[0].status,'PROPOSED');const bad=result();bad.fact_proposals=[{field:'line',value:'AUTO',confidence:.99,evidence_text:'vehicle coverage',message_id:'in'}];assert.throws(()=>validateReasoning(bad,{messages:[{id:'in',direction:'inbound',body:'I am shopping for Auto insurance.'}],known_answers:{line:{status:'UNKNOWN',value:null}},do_not_reask:[]}),/unsupported_evidence/);});
test('invalid fact diagnostics preserve only the safe field identifier',()=>{const r=result();r.fact_proposals=[{field:'annual_mileage',value:'12,000 miles',confidence:.99,evidence_text:'12,000 miles',message_id:'in'}];let error;try{validateReasoning(r,{messages:[{id:'in',direction:'inbound',body:'I drive about 12,000 miles a year.'}],known_answers:{annual_mileage:{status:'UNKNOWN',value:null}},do_not_reask:[]});}catch(e){error=e;}assert.equal(error?.message,'invalid_fact_value');assert.equal(error?.validation_field,'annual_mileage');const safe=safeProviderFailure(error);assert.deepEqual(safe,{error:'invalid_fact_value',validation_field:'annual_mileage'});assert.doesNotMatch(JSON.stringify(safe),/12,000/);});
test('direction is not evidence, unsupported dates rejected',()=>{const r=result();r.fact_proposals=[{field:'vehicle_ownership',value:'financed',confidence:1,evidence_text:'ask if financed',message_id:'direction'}];assert.throws(()=>validateReasoning(r,{messages:[],known_answers:{},do_not_reask:[]}),/unsupported_evidence/);r.fact_proposals=[{field:'renewal_date',value:'2026-02-30',confidence:1,evidence_text:'February',message_id:'in'}];assert.throws(()=>validateReasoning(r,{messages:[{id:'in',direction:'inbound',body:'February'}],known_answers:{},do_not_reask:[]}),/invalid_fact_date/);});
test('stale suggestion cannot be used after new inbound',async()=>{const f=await setup();try{const r=await f.svc.act({action:'analyze',id:'one'});f.conversation.signal.revision++;await f.store.setJSON(key,f.conversation);await assert.rejects(f.svc.select('one',r.suggestion.id,r.suggestion.result.reply.draft),/stale/);}finally{f.sql.close();}});
test('monthly hard ceiling blocks model and leaves existing reply intact',async()=>{const f=await setup();try{f.env.CF_AI_MONTHLY_BUDGET_USD='.00001';await assert.rejects(f.svc.act({action:'analyze',id:'one'}),/budget/);assert.equal(f.calls(),0);assert.equal((await f.store.get(key)).signal.reply,'What has you looking?');}finally{f.sql.close();}});
test('concurrent identical requests cost once',async()=>{
 const f=await setup();let release;const gate=new Promise(resolve=>{release=resolve;});
 let started;const entered=new Promise(resolve=>{started=resolve;});
 const svc=copilotService(f.repo,f.env,{provider:async(...args)=>{started();await gate;return f.provider(...args);}});
 let first;
 try{
  first=svc.act({action:'analyze',id:'one'});await entered;
  await assert.rejects(svc.act({action:'analyze',id:'one'}),/ai_request_already_attempted|ai_request_in_progress/);
  release();const completed=await first;
  const cached=await svc.act({action:'analyze',id:'one'});
  assert.equal(cached.cached,true);assert.equal(cached.suggestion.id,completed.suggestion.id);assert.equal(f.calls(),1);
 }finally{release();if(first)await first.catch(()=>{});f.sql.close();}
});
test('provider failure keeps a bounded charge reservation; no automatic retry',async()=>{const f=await setup();try{let n=0;const s=copilotService(f.repo,f.env,{provider:async()=>{n++;throw Error('provider_timeout');}});await assert.rejects(s.act({action:'analyze',id:'one'}));await assert.rejects(s.act({action:'analyze',id:'one'}));assert.equal(n,1);assert.equal((await f.store.get(key)).signal.draft_status,'pending');assert.equal((await s.metrics()).failures,1);}finally{f.sql.close();}});
test('producer auth, same origin and opportunity scope required',async()=>{const f=await setup();try{const req=()=>new Request('https://example.test/api/solo-desk/copilot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:'one',action:'analyze'})});assert.notEqual((await handleSoloDesk({request:req(),env:f.env})).status,200);await assert.rejects(f.svc.act({id:'not-owned',action:'analyze'}));assert.equal(f.calls(),0);}finally{f.sql.close();}});
test('minimal context excludes raw prohibited attributes and producer identifiers',async()=>{const f=await setup();try{f.conversation.signal.facts={line:'AUTO',credit:'EXCLUDE_CREDIT',dob:'EXCLUDE_DOB',occupation:'EXCLUDE_JOB'};await f.store.setJSON(key,f.conversation);const c=await copilotContext(f.repo,f.store,f.env,'one');assert.doesNotMatch(JSON.stringify(c.data),/EXCLUDE_|12025550199|cohort|api.key/i);assert.match(minimize('Email me a@b.com. SSN 123-45-6789.'),/omitted/);}finally{f.sql.close();}});
test('adapter is stateless and bounded; API key exists only in outbound server header',async()=>{const f=await setup();try{let count=0;const r=await reasonWithProvider({messages:[]},aiConfig(f.env),{env:f.env,fetch:async(url,init)=>{count++;const p=JSON.parse(init.body);assert.equal(p.store,false);assert.equal(p.tools,undefined);assert.equal(p.max_output_tokens,2000);assert.equal(p.text.format.strict,true);assert.doesNotMatch(init.body,/synthetic-only-key/);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(result())}]}],usage:{input_tokens:500,output_tokens:200}});}});assert.equal(count,1);assert.equal(r.usage.input_tokens,500);assert.equal(JSON.stringify(r).includes(f.env.OPENAI_API_KEY),false);}finally{f.sql.close();}});
test('adapter rejects refusal, malformed output and huge input without hidden loops',async()=>{const f=await setup();try{let count=0;const options={env:f.env,fetch:async()=>{count++;return Response.json({status:'completed',output:[{content:[{type:'refusal'}]}]});}};await assert.rejects(reasonWithProvider({},aiConfig(f.env),options),/refusal/);assert.equal(count,1);await assert.rejects(reasonWithProvider({body:'x'.repeat(40000)},aiConfig(f.env),options),/context_too_large/);assert.equal(count,1);}finally{f.sql.close();}});
test('UI separates generation from approval and exposes labelled direction and live status',()=>{const html=copilotPanel();assert.match(html,/Add direction/);assert.match(html,/aria-live="polite"/);assert.doesNotMatch(html,/data-sms-action="approve_send"|OPENAI_API_KEY/);});
test('extracted carrier/vehicle are not asked again within the same recommendation',()=>{const r=result();r.fact_proposals=[{field:'current_carrier',value:'Allstate',confidence:.99,evidence_text:'Allstate',message_id:'in'}];r.reply.asks=['current_carrier'];const v=validateReasoning(r,{messages:[{id:'in',direction:'inbound',body:'Allstate'}],known_answers:{current_carrier:{status:'UNKNOWN',value:null}},do_not_reask:[]});assert.equal(v.fact_proposals[0].status,'PROPOSED');assert.equal(v.reply.draft,'');});
test('authenticated cross-origin Copilot requests rejected',async()=>{const f=await setup();try{const request=new Request('https://example.test/api/solo-desk/copilot',{method:'POST',headers:{authorization:'Bearer '+f.env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN,origin:'https://other.test','content-type':'application/json'},body:JSON.stringify({action:'analyze',id:'one'})});assert.equal((await handleSoloDesk({request,env:f.env})).status,403);}finally{f.sql.close();}});
test('stale source facts block selected draft approval but allow explicit manual replacement',async()=>{const f=await setup();try{
 const r=await f.svc.act({action:'analyze',id:'one'});let sends=0;const options={env:f.env,store:f.store,sendSignal:async()=>{sends++;return {providerMessageId:'manual'};}};
 assert.equal((await handleSmsSignal(f.req({action:'edit',opportunity_id:'one',conversation_id:cid,revision:1,copilot_id:r.suggestion.id,message:r.suggestion.result.reply.draft}),options)).status,200);
 f.sql.prepare('UPDATE cf_solo_sources SET summary_json=?').run(JSON.stringify({...f.pilot,raw_facts:{annual_mileage:12000}}));
 assert.equal((await handleSmsSignal(f.req({action:'approve_send',opportunity_id:'one',conversation_id:cid,revision:2}),options)).status,409);assert.equal(sends,0);
 assert.equal((await handleSmsSignal(f.req({action:'edit',opportunity_id:'one',conversation_id:cid,revision:2,message:'Thanks, I will review what you shared.'}),options)).status,200);
 assert.equal((await handleSmsSignal(f.req({action:'approve_send',opportunity_id:'one',conversation_id:cid,revision:3}),options)).status,200);assert.equal(sends,1);
 }finally{f.sql.close();}});
test('provider timeout aborts once without retry',async()=>{const f=await setup();try{let calls=0;await assert.rejects(reasonWithProvider({}, {...aiConfig(f.env),timeout:5},{env:f.env,fetch:async(_url,{signal})=>{calls++;return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('abort'))));}}),/provider_timeout/);assert.equal(calls,1);}finally{f.sql.close();}});
test('concurrent distinct requests cannot overspend the reserved budget',async()=>{const f=await setup();try{f.env.CF_AI_MONTHLY_BUDGET_USD='.012';const r=await Promise.allSettled([f.svc.act({action:'analyze',id:'one',direction:'shorter'}),f.svc.act({action:'analyze',id:'one',direction:'warmer'})]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.calls(),1);}finally{f.sql.close();}});
test('per-producer rate limit bounds explicit regeneration without breaking manual workflow',async()=>{const f=await setup();try{for(let n=0;n<6;n++)await f.svc.act({action:'analyze',id:'one',direction:'variation '+n});await assert.rejects(f.svc.act({action:'analyze',id:'one',direction:'seventh'}),/rate_limited/);assert.equal(f.calls(),6);assert.equal((await f.store.get(key)).signal.reply,'What has you looking?');}finally{f.sql.close();}});
test('Copilot usage reads request history without LIKE ESCAPE dependency',async()=>{const f=await setup();try{await f.svc.act({action:'analyze',id:'one'});const m=await f.svc.metrics();assert.equal(m.evaluation.analyzed_inbounds,1);assert.equal(m.failures,0);}finally{f.sql.close();}});
test('usage tolerates legacy complete records without newer validation fields',async()=>{const f=await setup();try{const month=new Date().toISOString().slice(0,7);await f.store.setJSON('signal-copilot/qa/requests/'+('c'.repeat(64)),{id:'c'.repeat(64),opportunity_id:'one',conversation_id:cid,inbound_message_id:'in-legacy',at:month+'-01T00:00:00.000Z',status:'complete',result:{reply:{draft:'Legacy'}}});const m=await f.svc.metrics();assert.equal(m.failures,0);assert.equal(m.repeat_rejections,0);assert.equal(m.evaluation.fact_conflicts,0);}finally{f.sql.close();}});
test('usage remains available when optional outcome join fails',async()=>{const f=await setup();try{await f.svc.act({action:'analyze',id:'one'});const degraded={...f.repo,rows:async(q,...values)=>{if(q.includes('cf_acq_opportunity_measurements'))throw Error('measurement unavailable');return f.repo.rows(q,...values);}};const m=await copilotService(degraded,f.env).metrics();assert.equal(m.evaluation.analyzed_inbounds,1);assert.equal(m.evaluation.outcome_join_available,false);assert.equal(m.evaluation.outcome_records,null);}finally{f.sql.close();}});
test('usage outcomes remain unknown when canonical measurement is absent',async()=>{const f=await setup();try{await f.svc.act({action:'analyze',id:'one'});const m=await f.svc.metrics();assert.equal(m.evaluation.analyzed_inbounds,1);assert.equal(m.evaluation.quotes,null);assert.equal(m.evaluation.binds,null);assert.equal(m.evaluation.sent_inbounds,0);}finally{f.sql.close();}});

for(const scenario of ['eligible','off','CONTROL','OTHER','no_inbound','STOP','opted_out','suppressed','sending','delivery_review','missing_message'])test('Work Copilot visibility matches server eligibility: '+scenario,async()=>{const f=await setup();try{
 if(scenario==='off')f.env.CF_AI_ENABLED='0';
 if(scenario==='CONTROL'||scenario==='OTHER'){f.pilot.cohort=scenario;f.sql.prepare('UPDATE cf_solo_sources SET summary_json=?').run(JSON.stringify(f.pilot));}
 if(scenario==='no_inbound')f.conversation.signal.latest_inbound='';
 if(scenario==='STOP')f.conversation.signal.decision_2='STOP';
 if(scenario==='opted_out')f.conversation.smsConsent={status:'opted_out'};
 if(scenario==='suppressed')f.conversation.signal.contact_suppressed=true;
 if(['sending','delivery_review'].includes(scenario))f.conversation.signal.draft_status=scenario;
 if(scenario==='missing_message')f.conversation.transcript=[];
 await f.store.setJSON(key,f.conversation);
 const d=await producerWorkspace(f.repo,f.env).detail('one');assert.equal(d.copilot_enabled,scenario==='eligible');assert.equal(f.calls(),0);
}finally{f.sql.close();}});
