import test from 'node:test';
import assert from 'node:assert/strict';
import {decideSignal,matchTemplate,DEFAULT_TEMPLATES,compliance,extractFacts,observeOutbound,signalMetrics,D2} from '../server/sms-signal-core.mjs';
import {handleRingCentralWebhook} from '../server/ringcentral-sms-connection-core.mjs';
import {handleSmsSignal} from '../server/sms-signal-api.mjs';
import {sendSmsThroughGateway} from '../server/sms-outbound-gateway.mjs';
const at='2026-09-24T12:00:00Z';
const probe='Hi Test, Dylan with Farmers. Are you still open to comparing your insurance, or are you all set now?';
const fresh='Is this for auto, home, or both?';
const context=(previous=probe,signal={})=>({transcript:[{direction:'outbound',body:previous,occurredAt:at}],signal});
const decide=(body,previous=probe,signal={})=>decideSignal(context(previous,signal),body,{now:at,messageId:'test'}).signal;
for(const [reply,action] of [['Yes','ASK_ONE_QUESTION'],['Maybe','ASK_ONE_QUESTION'],['Call me','CALL'],['My renewal is next week','CALL'],['My policy cancels Friday','CALL'],['I just renewed. Call me in December.','LATER'],["I'm all set, thanks.",'CLOSE'],['Not interested','CLOSE'],['STOP','STOP'],['Wrong number','CLOSE'],["I'm already with Farmers.",'CLOSE']])test(`route ${reply}`,()=>assert.equal(decide(reply).decision_2,action));
test('fresh line reply uses preceding question',()=>{const s=decide('Auto',fresh);assert.equal(s.facts.line,'AUTO');assert.equal(s.reply_goal,'DETECT_TIMING');assert.equal(s.az_recommended_stage,'ENGAGED');});
test('Home requires supported context',()=>{assert.equal(decide('Home',fresh).facts.line,'HOME');assert.equal(decide('Home','Where are you?').facts.line,undefined);assert.equal(decide('Home','Where are you?').human_required,true);});
test('No depends on previous question',()=>{assert.equal(decide('No').decision_2,'CLOSE');assert.equal(decide('No',fresh).classification,'review');});
test('recognition normalizes case punctuation and variable name',()=>assert.equal(matchTemplate(probe.toUpperCase()).template_id,'AZ-AGED-P1'));
test('unknown and overlapping templates fail closed',()=>{assert.equal(matchTemplate('Hi'),null);assert.equal(matchTemplate(fresh,[DEFAULT_TEMPLATES[0],{...DEFAULT_TEMPLATES[0],template_id:'AZ-OTHER'}]),null);});
test('wrong-number, optout and autoresponder deterministic',()=>{for(const t of ['Please remove me','Do not contact me','Don’t text me again','UNSUBSCRIBE'])assert.equal(compliance(t),'opt_out');assert.equal(compliance("I'm Driving - Sent from My Car"),'automatic_response');assert.equal(compliance('You have the wrong person'),'wrong_number');});
test('autoresponder does not erase state or count engagement',()=>{const s=decide("I'm Driving - Sent from My Car",probe,{meaningful_replies:2,az_recommended_stage:'ENGAGED'});assert.equal(s.meaningful_replies,2);assert.equal(s.az_recommended_stage,'ENGAGED');assert.equal(s.decision_2,undefined);});
test('zero repeat uses memory and sent-goal history',()=>{const s=decide('Yes',probe,{facts:{line:'AUTO',current_carrier:'AAA',timing:{raw:'someday'}},asked_goals:['DETECT_PRICE']});assert.equal(s.decision_2,'CALL');assert.equal(s.reply,'');});
test('depth counts sent questions not generated drafts',()=>{assert.equal(decide('Yes',probe,{questions_sent:3}).decision_2,'CALL');assert.equal(decide('Yes',probe,{questions_sent:0}).decision_2,'ASK_ONE_QUESTION');});
test('future dates retain precision without fabricating day',()=>{const s=decide('Call me in December');assert.equal(s.future_month,'2026-12');assert.equal(s.future_date,null);assert.equal(s.az_recommended_stage,'FUTURE_BIND');});
test('quotes use objection context',()=>{const old={managed:true,az_confirmed_stage:'QUOTE_SENT'};const a=decide('Too expensive',probe,old);assert.equal(a.quote_response,'PRICE');assert.equal(a.reply_goal,'DETECT_PRICE_TARGET');assert.equal(a.az_recommended_stage,'QUOTE_SENT');for(const reply of ['Does this cover water damage?','Ready to bind'])assert.equal(decide(reply,probe,old).human_required,true);});
test('fact extraction does not invent premium period',()=>{const s=decide('I pay $287 with GEICO and have 2 vehicles and 2 drivers',fresh);assert.equal(s.facts.current_premium,287);assert.equal(s.facts.premium_period,undefined);assert.equal(s.facts.current_carrier,'GEICO');assert.equal(s.facts.vehicle_count,2);});
test('email-only preference suppresses SMS draft',()=>{const s=decide('Yes, email only');assert.equal(s.reply,'');assert.equal(s.facts.preferred_channel,'EMAIL');});
test('stage mismatch never claims AZ changed',()=>{const out=observeOutbound({signal:{meaningful_replies:1,az_recommended_stage:'ENGAGED'}},{body:"Just closing the loop — if you'd still like me to take a look, reply YES. Otherwise I'll close this out.",messageId:'p2',occurredAt:at});assert.equal(out.mismatch,true);assert.equal(out.conversation.signal.az_confirmed_stage,undefined);});
function store(){const rows=new Map();return {rows,async get(k){return structuredClone(rows.get(k)||null)},async setJSON(k,v,o={}){if(o.onlyIfNew&&rows.has(k))throw Error('exists');rows.set(k,structuredClone(v));},async delete(k){rows.delete(k)},async list({prefix='',limit=500}={}){return {blobs:[...rows.keys()].filter(k=>k.startsWith(prefix)).slice(0,limit).map(key=>({key}))}}};}
const env={CF_SMS_SIGNAL_ENABLED:'1',RINGCENTRAL_FROM_NUMBER:'+12025550100',RINGCENTRAL_WEBHOOK_VALIDATION_TOKEN:'test-validation',RINGCENTRAL_CONVERSATION_HASH_SECRET:'test-hash-secret-at-least-16',COVERAGEFIT_PRODUCER_ACCESS_TOKEN:'test-producer-key-at-least-24-characters'};
async function hook(st,direction,body,id){const outbound=direction==='Outbound';return handleRingCentralWebhook(new Request('https://example.test/api/sms/ringcentral/webhook',{method:'POST',headers:{'content-type':'application/json','validation-token':env.RINGCENTRAL_WEBHOOK_VALIDATION_TOKEN},body:JSON.stringify({body:{type:'SMS',direction,id,from:{phoneNumber:outbound?env.RINGCENTRAL_FROM_NUMBER:'+12025550101'},to:[{phoneNumber:outbound?'+12025550101':env.RINGCENTRAL_FROM_NUMBER}],subject:body,creationTime:at}})}),{env,store:st,now:at,fetch:async()=>{throw Error('Live external call forbidden in tests')}});}
const conversation=st=>[...st.rows.values()].find(x=>x.id?.startsWith('sms-live-'));
async function api(st,b,extra={}){return handleSmsSignal(new Request('https://example.test/api/sms/signal',{method:b?'POST':'GET',headers:{authorization:`Bearer ${env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN}`,origin:'https://example.test','content-type':'application/json'},...(b?{body:JSON.stringify(b)}:{})}),{env,store:st,now:at,...extra});}
test('webhook end to end: AZ probe, draft, approve once, zero repeat, optout',async()=>{
 const st=store();assert.equal((await hook(st,'Outbound',probe,'o1')).status,200);
 const inbound=await (await hook(st,'Inbound','Yes','i1')).json();assert.equal(inbound.replied,false);assert.equal(inbound.decision_2,'ASK_ONE_QUESTION');
 assert.equal((await (await hook(st,'Inbound','Yes','i1')).json()).deduped,true);
 let c=conversation(st);assert.equal(c.signal.questions_sent,undefined);let sends=0;
 const b={action:'approve_send',conversation_id:c.id,revision:c.signal.revision};
 const sent=await api(st,b,{sendSignal:async()=>{sends++;return {providerMessageId:'sent1'}}});assert.equal(sent.status,200);assert.equal((await api(st,b)).status,409);assert.equal(sends,1);
 c=conversation(st);assert.equal(c.signal.questions_sent,1);
 await hook(st,'Inbound','Auto','i2');c=conversation(st);assert.equal(c.signal.facts.line,'AUTO');assert.equal(c.signal.reply_goal,'DETECT_TIMING');
 await hook(st,'Inbound','Do not text me','i3');c=conversation(st);assert.equal(c.signal.decision_2,'STOP');assert.equal(c.smsConsent.status,'opted_out');assert.equal(c.signal.reply,'');
 assert.equal((await api(st,{action:'edit',conversation_id:c.id,revision:c.signal.revision,message:'Hello'})).status,409);
});
test('manual takeover invalidates draft and blocks new drafts',async()=>{const st=store();await hook(st,'Outbound',probe,'o1');await hook(st,'Inbound','Yes','i1');await hook(st,'Outbound','I will handle this personally','m1');await hook(st,'Inbound','Auto','i2');assert.equal(conversation(st).signal.reply,'');assert.equal(conversation(st).signal.human_active,true);});
test('wrong number is locally suppressed including gateway',async()=>{const st=store();await hook(st,'Outbound',probe,'o');await hook(st,'Inbound','Wrong number','i');const c=conversation(st);assert.equal(c.signal.contact_suppressed,true);await assert.rejects(sendSmsThroughGateway({to:c.contactPhone,message:'Hello',origin:'producer_console',workflow:'signal_review_v1',replyRoute:'producer',ownershipEffect:'preserve',idempotencyKey:'test-wrong-number'},{env,store:st}),e=>e.code==='sms_channel_suppressed');});
test('AZ sync requires current revision and correct stage',async()=>{const st=store();await hook(st,'Outbound',probe,'o');await hook(st,'Inbound','Call me','i');const c=conversation(st);assert.equal((await api(st,{action:'mark_az_updated',conversation_id:c.id,revision:c.signal.revision,stage:'CLOSED'})).status,409);assert.equal((await api(st,{action:'mark_az_updated',conversation_id:c.id,revision:c.signal.revision,stage:'ENGAGED'})).status,200);assert.equal(conversation(st).signal.az_sync_status,'confirmed');});
test('thread contention fails retryably without processing or sending',async()=>{const st=store();await hook(st,'Outbound',probe,'o');const c=conversation(st);await st.setJSON('sms-signal/locks/'+c.id,{at});assert.equal((await hook(st,'Inbound','Yes','i')).status,503);assert.equal(st.rows.has('sms-live-events/i'),false);});
test('missing history routes human review, never legacy automatic welcome',async()=>{const st=store();const r=await hook(st,'Inbound','Home','i');assert.equal(r.status,200);assert.equal(conversation(st).signal.human_required,true);assert.equal(conversation(st).signal.reply,'');});
test('simulation neither sends nor mutates conversation data',async()=>{const st=store();const r=await api(st,{action:'simulate',previous_outbound:fresh,inbound:'Home'});assert.equal(r.status,200);assert.equal(st.rows.size,0);});
test('unknown CRM conversions are null and auto replies not positive',()=>{const m=signalMetrics([{direction:'outbound',conversation_id:'a',source_template:'AZ-AGED-P1'},{direction:'inbound',conversation_id:'a',classification:'automatic_response'}]);assert.equal(m.reply_rate,0);assert.equal(m.quote_sent_to_won,null);assert.equal(m.positive_signal_rate,null);});
test('send failure cannot be retried through repeated approval',async()=>{const st=store();await hook(st,'Outbound',probe,'o');await hook(st,'Inbound','Yes','i');const c=conversation(st),b={action:'approve_send',conversation_id:c.id,revision:c.signal.revision};assert.equal((await api(st,b,{sendSignal:async()=>{throw Error('timeout')}})).status,502);assert.equal((await api(st,b)).status,409);assert.equal(conversation(st).signal.draft_status,'delivery_review');});
test('negative carrier statements and deductible dollars are not invented facts',()=>{assert.notEqual(decide("I'm not with Farmers").classification,'existing_farmers');const f=extractFacts('I want a $500 deductible',probe,{},at).facts;assert.equal(f.current_premium,undefined);assert.equal(f.deductible_target,500);assert.equal(compliance("This isn't what I wanted"),'');});
test('quote price target is captured in context then escalated',()=>{const s=decide('140','Is there a monthly number you are trying to stay under?',{managed:true,pending_goal:'DETECT_PRICE_TARGET',az_confirmed_stage:'QUOTE_SENT'});assert.equal(s.facts.price_target,140);assert.equal(s.decision_2,'CALL');});
test('legacy known line/carrier is reused',()=>{const c=context();c.agedLead={lineOfBusiness:'auto',carrier:{carrier:'AAA'}};const s=decideSignal(c,'Yes',{now:at}).signal;assert.equal(s.facts.line,'AUTO');assert.equal(s.facts.current_carrier,'AAA');assert.equal(s.reply_goal,'DETECT_TIMING');});
test('natural optout needs no history retrieval',async()=>{const st=store();let fetched=false;const res=await hook(st,'Inbound','Please remove me','stop-alone');assert.equal(res.status,200);assert.equal(conversation(st).signal.decision_2,'STOP');});
test('API rejects unauthenticated and cross-origin mutations',async()=>{const st=store();assert.equal((await handleSmsSignal(new Request('https://example.test/api/sms/signal'),{env,store:st})).status,401);assert.equal((await handleSmsSignal(new Request('https://example.test/api/sms/signal',{method:'POST',headers:{authorization:`Bearer ${env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN}`,origin:'https://evil.test'},body:'{}'}),{env,store:st})).status,403);});
test('signal-managed conversations reject legacy programmatic sending',async()=>{const st=store();await hook(st,'Outbound',probe,'o');const c=conversation(st);await assert.rejects(sendSmsThroughGateway({to:c.contactPhone,message:'Question?',origin:'appointment',workflow:'callback',replyRoute:'appointment',ownershipEffect:'preserve',idempotencyKey:'test-block-legacy'},{env,store:st}),e=>e.code==='sms_automation_paused');});
test('prior transcript facts backfill memory before asking again',async()=>{const st=store();await hook(st,'Outbound',fresh,'o1');await hook(st,'Inbound','Auto','i1');let c=conversation(st);c.signal.facts={};await st.setJSON('sms-live-conversations/'+c.id,c);await hook(st,'Inbound','Yes','i2');c=conversation(st);assert.equal(c.signal.facts.line,'AUTO');assert.notEqual(c.signal.reply_goal,'IDENTIFY_LINE');});
test('a new campaign outbound invalidates an older pending draft',async()=>{const st=store();await hook(st,'Outbound',probe,'o');await hook(st,'Inbound','Yes','i');const old=conversation(st);await hook(st,'Outbound',probe,'o2');assert.equal(conversation(st).signal.draft_status,'none');assert.equal((await api(st,{action:'approve_send',conversation_id:old.id,revision:old.signal.revision})).status,409);});
test('future callback next week remains scheduled rather than call now',()=>assert.equal(decide('next week','What month should I check back?',{managed:true,pending_goal:'FUTURE_CALLBACK_DATE'}).decision_2,'LATER'));

const fresh2='Hi Test, just following up on your request. If it’s easier, we can handle most of this by text. Are you mainly looking at auto, home, or both?';
for(const [previous,id] of [[fresh,'AZ-FRESH-01'],[fresh2,'AZ-FRESH-02']]){
 for(const [reply,action,stage,line,channel,goal] of [
  ['Auto','ASK_ONE_QUESTION','ENGAGED','AUTO',undefined,'DETECT_TIMING'],
  ['Both','ASK_ONE_QUESTION','ENGAGED','HOME_AUTO',undefined,'DETECT_TIMING'],
  ['Text is easier.','ASK_ONE_QUESTION','ENGAGED',undefined,'TEXT','IDENTIFY_LINE'],
  ['Text','ASK_ONE_QUESTION','ENGAGED',undefined,'TEXT','IDENTIFY_LINE'],
  ['Call me now.','CALL','ENGAGED'],
  ['Already got insurance.','CLOSE','CLOSED'],
  ['Not interested.','CLOSE','CLOSED'],
  ['STOP','STOP','STOP']
 ])test(`${id}: ${reply}`,()=>{
  const s=decide(reply,previous);assert.equal(s.source_template,id);assert.equal(s.source_campaign,'AZ-FRESH');assert.equal(s.decision_2,action);assert.equal(s.az_recommended_stage,stage);
  if(line)assert.equal(s.facts.line,line);if(channel)assert.equal(s.facts.preferred_channel,channel);if(goal)assert.equal(s.reply_goal,goal);
  if(action==='ASK_ONE_QUESTION'){assert.equal((s.reply.match(/\?/g)||[]).length,1);assert.doesNotMatch(s.reply,/what (?:day|time)|schedule/i);}
  if(action==='CALL')assert.ok(['HIGH','URGENT'].includes(s.priority));if(action==='STOP')assert.equal(s.reply,'');
 });
 test(`${id} after engagement flags campaign collision`,()=>{const o=observeOutbound({signal:{meaningful_replies:1,az_recommended_stage:'ENGAGED'}},{body:previous,messageId:'fresh-collision',occurredAt:at});assert.equal(o.mismatch,true);assert.deepEqual(o.conversation.signal.stage_mismatch_context,{inferred_stage:'ENGAGED',observed_template:id,expected_stage:'CONTACT_ATTEMPT'});assert.equal(o.conversation.signal.az_confirmed_stage,undefined);});
}
test('seven registry templates include distinct fresh attempts',()=>{assert.deepEqual(DEFAULT_TEMPLATES.map(t=>t.template_id),['AZ-FRESH-01','AZ-FRESH-02','AZ-AGED-P1','AZ-AGED-P2','AZ-QUOTE-01','AZ-FUTURE-01','AZ-CALLBACK-01']);const t=matchTemplate(fresh2);assert.equal(t.purpose,'FRESH_SECONDARY_CONTACT');assert.equal(t.expected_az_stage,'CONTACT_ATTEMPT');assert.equal(t.default_reply_goal,'IDENTIFY_LINE');});
test('saved registry gains Fresh #2 without overriding custom or disabled entries',async()=>{const {templatesFor}=await import('../server/sms-signal-service.mjs');const st=store();const saved=DEFAULT_TEMPLATES.filter(t=>t.template_id!=='AZ-FRESH-02').map(t=>({...t,active:false}));await st.setJSON('sms-signal/templates',{templates:saved});const rows=await templatesFor(st);assert.equal(rows.length,7);assert.equal(rows.find(t=>t.template_id==='AZ-FRESH-01').active,false);assert.equal(rows.find(t=>t.template_id==='AZ-FRESH-02').active,true);});
test('fresh exhausted to awaiting signal uses aged context distinctly',()=>{const o=observeOutbound({signal:{az_confirmed_stage:'AWAITING_SIGNAL',az_inferred_stage:'AWAITING_SIGNAL',meaningful_replies:0}},{body:probe,messageId:'aged-after-fresh',occurredAt:at});assert.equal(o.mismatch,false);assert.equal(o.conversation.signal.source_campaign,'AZ-AGED-RECOVERY');assert.equal(o.conversation.signal.source_template,'AZ-AGED-P1');});
test('Fresh #2 text preference preserves known line without repeating question',()=>{const s=decide('Text is easier.',fresh2,{facts:{line:'AUTO'}});assert.equal(s.reply_goal,'DETECT_TIMING');assert.equal(s.facts.line,'AUTO');});
test('Fresh #2 webhook routes to review-only draft and manual AZ recommendation',async()=>{const st=store();await hook(st,'Outbound',fresh2,'fresh2-out');await hook(st,'Inbound','Both','fresh2-in');const s=conversation(st).signal;assert.equal(s.source_template,'AZ-FRESH-02');assert.equal(s.decision_2,'ASK_ONE_QUESTION');assert.equal(s.draft_status,'pending');assert.equal(s.az_sync_status,'pending');assert.equal(s.az_recommended_stage,'ENGAGED');assert.equal(s.questions_sent||0,0);});

// Original mandate acceptance examples, shared with the interactive simulator.
const {SIGNAL_SCENARIOS,simulateScenario}=await import('../server/sms-signal-scenarios.mjs');
for(const scenario of SIGNAL_SCENARIOS)test(`acceptance scenario: ${scenario.label}`,()=>{const result=simulateScenario(scenario.id,DEFAULT_TEMPLATES,at);assert.equal(result.passed,true,JSON.stringify(result.checks));assert.equal(result.sends,0);if(scenario.replay){assert.equal(result.processed_inbounds,1);assert.ok(result.trace.some(e=>e.event==='duplicate_skipped'));}});
test('named wrong-person denial suppresses without misreading ordinary disagreement',()=>{for(const body of ["This isn't Mike","This is not Julie","I'm not Mike"])assert.equal(decide(body).contact_suppressed,true);for(const body of ["This isn't what I wanted","This isn't Insurance","I'm not Interested"])assert.notEqual(compliance(body),'wrong_number');assert.equal(compliance("this isn't mike",{answers:{firstName:'Mike'}}),'wrong_number');});
test('payment urgency distinguishes price target from premium',()=>{const s=decide("I pay my insurance tomorrow. If it's lower than $140 let me know.");assert.equal(s.decision_2,'CALL');assert.equal(s.priority,'URGENT');assert.equal(s.facts.price_target,140);assert.equal(s.facts.current_premium,undefined);assert.equal(s.facts.payment_due_date,'2026-09-25');assert.equal(s.facts.renewal_date,undefined);const f=extractFacts('I pay $280 monthly and want under $200 monthly',probe,{},at).facts;assert.equal(f.current_premium,280);assert.equal(f.price_target,200);});
test('future quote opportunity retains quote and objection context',()=>{const s=decide('I will switch when I renew in December.',probe,{az_confirmed_stage:'QUOTE_SENT',last_quote:{summary:'Synthetic quote delivered'},facts:{line:'AUTO',current_carrier:'AAA',current_premium:280,preferred_channel:'TEXT'}});assert.equal(s.quote_response,'TIMING');assert.equal(s.future_opportunity.last_quote.summary,'Synthetic quote delivered');assert.equal(s.future_opportunity.last_objection,'TIMING');assert.equal(s.future_opportunity.future_month,'2026-12');assert.equal(s.future_opportunity.preferred_channel,'TEXT');});
test('quote-ready summary uses known facts and stops questioning',()=>{const s=decide('Yes',probe,{facts:{line:'AUTO',current_carrier:'GEICO',current_premium:287,timing:{raw:'renewal October 18'},vehicle_count:2,driver_count:2,shopping_reason:'price'}});assert.equal(s.quote_ready,true);assert.equal(s.quote_ready_context.vehicle_count,2);assert.equal(s.quote_ready_context.recommended_action,'Prepare quote');assert.equal(s.reply,'');assert.equal(s.az_recommended_stage,'QUOTE_READY');});
test('all simulator presets run through authenticated API without storage mutation',async()=>{const st=store();for(const x of SIGNAL_SCENARIOS){const r=await api(st,{action:'simulate_scenario',scenario_id:x.id});assert.equal(r.status,200);const b=await r.json();assert.equal(b.passed,true,JSON.stringify(b));}assert.equal(st.rows.size,0);});
test('signal event exposes decision evidence and transitions without raw message text',async()=>{const st=store();await hook(st,'Outbound',fresh,'audit-out');await hook(st,'Inbound','Auto','audit-in');const e=await st.get('sms-signal/events/audit-in');for(const type of ['sms_inbound_received','reply_classified','facts_extracted','decision_2_selected','reply_generated','az_stage_recommended'])assert.ok(e.transition_types.includes(type));assert.ok(e.fact_fields.includes('line'));assert.equal(e.recommended_az_stage,'ENGAGED');assert.equal(e.response_policy,'review_first');assert.ok(e.processed_at);assert.equal(e.latest_inbound,undefined);assert.equal(e.previous_outbound,undefined);});
test('manual quote summary is preserved without claiming CRM update',async()=>{const st=store();await hook(st,'Outbound',probe,'o');await hook(st,'Inbound','Yes','i');const c=conversation(st);const r=await api(st,{action:'record_quote',conversation_id:c.id,revision:c.signal.revision,summary:'Synthetic quote delivered by producer'});assert.equal(r.status,200);assert.equal(conversation(st).signal.last_quote.source,'manual_observation');assert.equal(conversation(st).signal.az_confirmed_stage,undefined);});

test('known structured renewal date satisfies timing and is not asked again',()=>{const s=decide('Yes',probe,{facts:{line:'AUTO',renewal_date:'2026-10-28'}});assert.notEqual(s.reply_goal,'DETECT_TIMING');});
test('first-party intake and entry commands remain on existing handlers',async()=>{const {signalInbound}=await import('../server/sms-signal-service.mjs');for(const keyword of ['BUYER','HOME','BUNDLE','AUTO','RUSH']){const r=await signalInbound({transcript:[]},{body:keyword,messageId:keyword,occurredAt:at},{env,store:store(),listSignalHistory:async()=>({records:[],hasMore:false})});assert.equal(r,null,keyword);}for(const type of ['coveragefit_homebuyer','coveragefit_home_review','coveragefit_bundle']){const r=await signalInbound({orchestration:{workflow:{type}},transcript:[]},{body:'October 12',messageId:type,occurredAt:at},{env,store:store()});assert.equal(r,null,type);}});
test('campaign-context AUTO still enters signal despite legacy intake keyword',async()=>{const {signalInbound}=await import('../server/sms-signal-service.mjs');const st=store();await hook(st,'Outbound',fresh,'o');const r=await signalInbound(conversation(st),{body:'AUTO',messageId:'i',occurredAt:at},{env,store:st});assert.equal(r.signal.source_template,'AZ-FRESH-01');assert.equal(r.signal.decision_2,'ASK_ONE_QUESTION');});
test('secure handoff token issuance and expiry remain intact',async()=>{const {createSmsHandoff,smsHandoffKey,smsHandoffIsFresh,SMS_HANDOFF_TOKEN_PATTERN}=await import('../server/sms-handoff-core.mjs');const st=store();const h=await createSmsHandoff({id:'synthetic-handoff',state:'coveragefit_ready',intent:'buyer',answers:{}},{store:st,now:at});assert.ok(SMS_HANDOFF_TOKEN_PATTERN.test(h.token));const record=await st.get(await smsHandoffKey(h.token));assert.equal(smsHandoffIsFresh(record,new Date(at)),true);assert.equal(smsHandoffIsFresh(record,new Date('2026-09-26T12:00:00Z')),false);});
test('old quote-ready status cannot survive STOP, close or future routing',()=>{for(const body of ['STOP','Not interested','Call me in December']){const s=decide(body,probe,{quote_ready:true});assert.equal(s.quote_ready,false);}});
test('wrong-number suppression persists on subsequent positive reply',()=>{const old=decide('Wrong number');const s=decide('Yes',probe,old);assert.equal(s.decision_2,'CLOSE');assert.equal(s.contact_suppressed,true);assert.equal(s.reply,'');});
test('manual follow-up rejects impossible dates and preserves month precision',async()=>{const st=store();await hook(st,'Outbound',probe,'o');await hook(st,'Inbound','Yes','i');const c=conversation(st);const b={action:'decide',conversation_id:c.id,revision:c.signal.revision,decision_2:'LATER'};assert.equal((await api(st,{...b,followup_date:'2026-02-31'})).status,422);assert.equal((await api(st,{...b,followup_date:'2026-12'})).status,200);const s=conversation(st).signal;assert.equal(s.future_opportunity.future_month,'2026-12');assert.equal(s.future_date,null);});
