import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveSmsOwnership,ownershipLabel} from '../server/sms-ownership.mjs';
import {DEFAULT_TEMPLATES} from '../server/sms-signal-core.mjs';
import {handleRingCentralWebhook} from '../server/ringcentral-sms-connection-core.mjs';
import {smsLiveConversationId,sendSmsThroughGateway} from '../server/sms-outbound-gateway.mjs';
import {handleSmsSignal} from '../server/sms-signal-api.mjs';
const at='2026-09-26T03:00:00Z', phone='+12025550199';
const fresh='Hi Andrew, Dylan with Farmers. I just tried calling about the insurance request you sent in. Is this for auto, home, or both?';
async function setup(enabled='0'){
 const rows=new Map(),st={async get(k){return structuredClone(rows.get(k)||null)},async setJSON(k,v,o={}){if(o.onlyIfNew&&rows.has(k))throw Error('exists');rows.set(k,structuredClone(v))},async delete(k){rows.delete(k)},async list({prefix=''}){return {blobs:[...rows.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}};
 let cohort=null,sends=0,history=[];
 const env={CF_SMS_SIGNAL_ENABLED:enabled,CF_SMS_SIGNAL_PILOT_ONLY:'1',RINGCENTRAL_FROM_NUMBER:'+12025550100',RINGCENTRAL_WEBHOOK_VALIDATION_TOKEN:'synthetic-validation',RINGCENTRAL_CONVERSATION_HASH_SECRET:'synthetic-ownership-secret',RINGCENTRAL_CLIENT_ID:'synthetic-owner-id',RINGCENTRAL_CLIENT_SECRET:'synthetic-owner-secret',RINGCENTRAL_JWT_TOKEN:'synthetic-owner-jwt',COVERAGEFIT_PRODUCER_ACCESS_TOKEN:'synthetic-producer-access-long-enough',COVERAGEFIT_DB:{prepare:()=>({bind:()=>({all:async()=>({results:cohort?[{summary_json:JSON.stringify({pilot_id:'SIGNAL_DISTRICT_PILOT_1',pilot_phase:'TEST',cohort})}]:[]})})})}};
 const id=await smsLiveConversationId(phone,env.RINGCENTRAL_FROM_NUMBER,env.RINGCENTRAL_CONVERSATION_HASH_SECRET),key='sms-live-conversations/'+id;
 const options={env,store:st,now:at,listSignalHistory:async()=>({records:history,hasMore:false}),fetchImpl:async(url)=>{if(String(url).endsWith('/oauth/token'))return Response.json({access_token:'fake',expires_in:3600});if(String(url).endsWith('/sms')){sends++;return Response.json({id:'fake-send-'+sends});}throw Error('Unexpected provider request: '+url);}};
 async function hook(direction,body,messageId){const out=direction==='Outbound';const r=await handleRingCentralWebhook(new Request('https://example.test/api/sms/ringcentral/webhook',{method:'POST',headers:{'content-type':'application/json','validation-token':env.RINGCENTRAL_WEBHOOK_VALIDATION_TOKEN},body:JSON.stringify({body:{type:'SMS',direction,id:messageId,from:{phoneNumber:out?env.RINGCENTRAL_FROM_NUMBER:phone},to:[{phoneNumber:out?phone:env.RINGCENTRAL_FROM_NUMBER}],subject:body,creationTime:at}})}),options);assert.equal(r.status,200);return r.json();}
 return {env,options,st,id,key,hook,get:()=>st.get(key),seed:c=>st.setJSON(key,{id,contactPhone:phone,businessPhone:env.RINGCENTRAL_FROM_NUMBER,state:'new',answers:{},transcript:[],...c}),enroll:c=>{cohort=c},history:h=>{history=h},sends:()=>sends};
}
for(const enabled of ['0','1'])test(`exact AgencyZoom Home regression, enabled=${enabled}`,async()=>{
 const f=await setup(enabled);await f.hook('Outbound',fresh,'az-out');const r=await f.hook('Inbound','Home','az-in');const c=await f.get();assert.equal(r.replied,false);assert.equal(c.smsOwnership.owner,'UNKNOWN');assert.equal(c.smsOwnership.basis,'agencyzoom_pending_enrollment');assert.equal(c.smsOwnership.agencyzoom_context,'AZ-FRESH-01');assert.equal(c.signal.reply,'');assert.equal(c.state,'new');assert.ok(c.transcript.some(x=>x.body==='Home'));assert.equal(f.sends(),0);assert.match(ownershipLabel(c.smsOwnership),/awaiting pilot enrollment/);
 const replay=await f.hook('Inbound','Home','az-in');assert.equal(replay.deduped,true);assert.equal(f.sends(),0);
});
test('inbound-only delivery recovers AgencyZoom outbound context before legacy routing',async()=>{const f=await setup();f.history([{id:'prior',direction:'Outbound',from:{phoneNumber:f.env.RINGCENTRAL_FROM_NUMBER},to:[{phoneNumber:phone}],subject:fresh,creationTime:at}]);await f.hook('Inbound','Home','recovered');assert.equal((await f.get()).smsOwnership.agencyzoom_context,'AZ-FRESH-01');assert.equal(f.sends(),0);});
for(const t of DEFAULT_TEMPLATES)test(`all registry families hold before enrollment: ${t.template_id}`,async()=>{const f=await setup();await f.hook('Outbound',t.message_pattern.join(' '),'out');await f.hook('Inbound','Yes','in');assert.equal((await f.get()).smsOwnership.agencyzoom_context,t.template_id);assert.equal(f.sends(),0);});
test('unknown Home cannot acquire first-party ownership from keyword or shared phone',async()=>{const f=await setup();await f.hook('Inbound','Home','unknown');const c=await f.get();assert.equal(c.smsOwnership.owner,'UNKNOWN');assert.equal(c.signal.reply,'');assert.equal(f.sends(),0);});
test('verified first-party Home still runs guided intake through the real gateway (fake provider)',async()=>{const f=await setup();await f.seed({orchestration:{ownership:{owner:'coveragefit',reason:'producer_started_workflow'},automationMode:'automated',workflow:{type:'coveragefit_home_review',state:'new',status:'active'}}});const r=await f.hook('Inbound','Home','first-party');const c=await f.get();assert.equal(c.smsOwnership.owner,'FIRST_PARTY_408');assert.equal(r.replied,true,JSON.stringify(c.deliveryFailure));assert.equal(f.sends(),1);assert.ok(c.transcript.some(x=>x.direction==='outbound'&&/own or rent/i.test(x.body)));});
for(const cohort of ['SIGNAL','CONTROL'])test(`late ${cohort} enrollment preserves Home and does not send retroactively`,async()=>{const f=await setup('1');await f.hook('Outbound',fresh,'out');await f.hook('Inbound','Home','early');f.enroll(cohort);assert.equal(f.sends(),0);await f.hook('Inbound','I am open to comparing','later');const c=await f.get();assert.equal(c.smsOwnership.owner,'DISTRICT_'+cohort);assert.equal(f.sends(),0);assert.ok(c.transcript.some(x=>x.body==='Home'));if(cohort==='SIGNAL'){assert.equal(c.signal.facts.line,'HOME');assert.notEqual(c.signal.reply_goal,'IDENTIFY_LINE');assert.equal(c.signal.draft_status,'pending');}else{assert.equal(c.signal.managed,false);assert.equal(c.signal.reply,'');assert.equal(c.signal.decision_2,null);}});
for(const cohort of [null,'CONTROL','SIGNAL'])test(`producer takeover outranks ${cohort||'unknown'}`,async()=>{const f=await setup('1');f.enroll(cohort);await f.hook('Outbound','I will personally handle this.','manual');await f.hook('Inbound','HOME','reply');const c=await f.get();assert.equal(c.smsOwnership.owner,'PRODUCER_OWNED');assert.equal(f.sends(),0);assert.equal(c.signal.reply,'');});
for(const cohort of [null,'CONTROL','SIGNAL'])for(const body of ['STOP','Wrong number','Auto Reply','spam'])test(`compliance ${body} before ${cohort||'unknown'} ownership`,async()=>{const f=await setup();f.enroll(cohort);await f.hook('Inbound',body,'safe');const c=await f.get();assert.equal(f.sends(),0);assert.ok(!c.signal?.reply);if(body==='STOP')assert.equal(c.smsConsent.status,'opted_out');if(body==='Wrong number'||body==='spam'){assert.equal(c.signal.contact_suppressed,true);await f.hook('Inbound','Home','post-suppression');assert.equal(f.sends(),0);}});
test('ambiguous template and failed enrollment lookup hold even explicit first-party state',async()=>{const c={outboundContext:{origin:'coveragefit',registrationId:'trusted'},transcript:[{direction:'outbound',body:fresh}]};const templates=[DEFAULT_TEMPLATES[0],{...DEFAULT_TEMPLATES[0],template_id:'AZ-OTHER'}];assert.equal((await resolveSmsOwnership(c,{}, {templates})).basis,'ambiguous_outbound_context');assert.equal((await resolveSmsOwnership({...c,id:'test'},{},{env:{COVERAGEFIT_DB:{prepare(){throw Error('unavailable')}}}})).basis,'enrollment_lookup_failed');});
test('stale snapshot and queued legacy retry cannot bypass pending ownership',async()=>{const f=await setup();await f.hook('Outbound',fresh,'out');await f.hook('Inbound','Home','in');const c=await f.get();await assert.rejects(sendSmsThroughGateway({to:phone,message:'Do you own or rent?',origin:'coveragefit',workflow:'coveragefit_home_review',replyRoute:'coveragefit',ownershipEffect:'preserve',idempotencyKey:'ownership-stale-retry'}, {...f.options,allowRegisteredRetry:true,conversationSnapshot:{...c,smsOwnership:null,transcript:[],lastInboundAt:'',orchestration:{ownership:{owner:'coveragefit'},automationMode:'automated'}}}),e=>e.code==='sms_automation_paused');assert.equal(f.sends(),0);});
test('stale unenrolled Signal draft cannot be approved or edited with broad flag on',async()=>{const f=await setup('1');await f.seed({signal:{managed:true,reply:'Is this auto?',revision:1,draft_status:'pending'}});for(const action of ['edit','approve_send']){const r=await handleSmsSignal(new Request('https://example.test/api/sms/signal',{method:'POST',headers:{authorization:'Bearer '+f.env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN,origin:'https://example.test','content-type':'application/json'},body:JSON.stringify({action,conversation_id:f.id,revision:1,message:'Test?'})}),f.options);assert.equal(r.status,409);}assert.equal(f.sends(),0);});
for(const owner of ['first_party','producer'])test(`STOP overrides ${owner} with Signal off`,async()=>{const f=await setup();await f.seed(owner==='first_party'?{outboundContext:{origin:'coveragefit',registrationId:'verified-web'}}:{orchestration:{ownership:{owner:'producer',reason:'producer_took_ownership'}}});await f.hook('Inbound','STOP','stop');assert.equal((await f.get()).smsConsent.status,'opted_out');await f.hook('Inbound','HOME','later');assert.equal(f.sends(),0);});
test('generic inferred workflow does not establish positive first-party ownership',async()=>{const c={state:'home_review_address_requested',intent:'home_review',orchestration:{ownership:{owner:'coveragefit',reason:'coveragefit_workflow'},workflow:{type:'coveragefit_home_review'}}};assert.equal((await resolveSmsOwnership(c)).owner,'UNKNOWN');});
test('recognized AgencyZoom history overrides stale first-party workflow',async()=>{const f=await setup();await f.seed({outboundContext:{origin:'coveragefit',registrationId:'old'},transcript:[{direction:'outbound',body:fresh,occurredAt:at},{direction:'outbound',body:'Do you own or rent?',kind:'automation',occurredAt:at}]});await f.hook('Inbound','Home','hold-old');assert.equal((await f.get()).smsOwnership.basis,'agencyzoom_pending_enrollment');assert.equal(f.sends(),0);});
test('explicit producer return releases stale human flag but cannot override CONTROL enrollment',async()=>{const {handleSmsProducerHandoff}=await import('../server/sms-producer-handoff-core.mjs');for(const cohort of [null,'CONTROL']){const f=await setup();f.enroll(cohort);await f.seed({state:'human_takeover',signal:{human_active:true,automation_lock:true,context_error:true},orchestration:{ownership:{owner:'producer',reason:'producer_took_ownership'},workflow:{type:'coveragefit_home_review',state:'home_review_address_requested'}}});const r=await handleSmsProducerHandoff(new Request('https://example.test/api/sms/producer-handoff',{method:'POST',headers:{authorization:'Bearer '+f.env.COVERAGEFIT_PRODUCER_ACCESS_TOKEN,origin:'https://example.test','content-type':'application/json'},body:JSON.stringify({action:'return_to_coveragefit',conversationId:f.id})}),f.options);assert.equal(r.status,200);const c=await f.get();assert.equal(c.signal.human_active,false);const o=await resolveSmsOwnership(c,{},f.options);assert.equal(o.owner,cohort?'DISTRICT_CONTROL':'FIRST_PARTY_408');assert.equal(f.sends(),0);}});
test('registered first-party callback copy is not misattributed to AgencyZoom',async()=>{const c={outboundContext:{origin:'appointment',registrationId:'verified-callback'},transcript:[{direction:'outbound',kind:'appointment',body:'Sure — is now a good time, or is there a better time today?'}]};assert.equal((await resolveSmsOwnership(c)).owner,'FIRST_PARTY_408');});
